export enum SessionStorageKeyE {
  CURRENT_ACCOUNT = 'CURRENT_ACCOUNT',
  KEYCLOAK_SYNCED = 'synced',
  KEYCLOAK_TOKEN = 'KEYCLOAK_TOKEN',
  KEYCLOAK_TOKEN_ID = 'KEYCLOAK_ID_TOKEN',
  KEYCLOAK_TOKEN_REFRESH = 'KEYCLOAK_REFRESH_TOKEN',
}