#! /bin/bash

cd $files

set -ex

echo "$hostname" > /etc/hostname
sed -i "s/raspberrypi/$hostname/g" /etc/hosts

systemctl enable systemd-networkd

mkdir -p /etc/systemd/network/
mkdir -p /etc/wpa_supplicant/

# Remove old way of configuring network
if [ -f /etc/network/interfaces ]; then
	rm /etc/network/interfaces
fi

cp network/01-wired.network /etc/systemd/network/
cp network/02-wireless.network /etc/systemd/network/

cp network/wpa_supplicant-country.conf /etc/wpa_supplicant/wpa_supplicant.conf
cp network/wpa_supplicant-wlan0.conf /etc/wpa_supplicant/

systemctl enable wpa_supplicant@wlan0

envsubst '${network_reboot_timeout}' < network-watchdog.sh > /root/network-watchdog.sh
chmod +x /root/network-watchdog.sh

cp network-watchdog.service  /etc/systemd/system/

systemctl enable network-watchdog

systemctl enable systemd-resolved
ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf

cp first-boot.sh /root/
chmod +x /root/first-boot.sh
cp first-boot.service /etc/systemd/system/

systemctl enable first-boot.service
