#! /bin/bash
cd $files

set -ex

cp timesyncd.conf /etc/systemd/

# Final timezone setting will be done after the image is deployed on a device
ln -nsf /usr/share/zoneinfo/America/Vancouver /var/localtime
ln -nsf /var/localtime /etc/localtime
