#! /bin/bash
cd $files

set -ex

cp launch-browser.sh $home_dir/
cp sites.txt /root/

# Updates auto-login for X11 to point to tty2
envsubst '${username}' < autologin@.service > /etc/systemd/system/autologin@.service

chown $username:$username $home_dir/launch-browser.sh

systemctl set-default graphical.target
gpasswd -a $username tty

mkdir -p /etc/systemd/system/getty.target.wants
ln -fs /etc/systemd/system/autologin@.service /etc/systemd/system/getty.target.wants/getty@tty2.service
