#! /bin/bash

cd $files

set -ex

apt-get -y --purge autoremove
apt-get clean

rm -rf /var/log/*
rm -rf /var/cache/man/*
rm -rf /var/lib/apt/lists/*

# Remove unsued documentation:
rm -rf /usr/share/doc

mkdir -p /var/log/nginx
mkdir -p /var/log/supervisor

if id -u pi > /dev/null 2>&1; then
	deluser --force pi
	rm -rf /home/pi
fi

# Remove non-english locales
shopt -s extglob
rm -rf /usr/share/locale/!(en|en*|locale.alias)
rm -rf /usr/share/i18n/locales/!(en|en*|translit)
