#! /bin/bash

cd $files

set -ex

apt-get -y --purge autoremove
apt-get clean

rm -rf /var/log/*
rm -rf /var/cache/man
rm -rf /var/lib/apt/lists/*

# Remove unsued documentation:
rm -rf /usr/share/doc
rm -rf /usr/share/man

mkdir -p /var/log/nginx
mkdir -p /var/log/supervisor

if id -u pi > /dev/null 2>&1; then
        deluser --force pi
        rm -rf /home/pi
fi

# Remove non-english locales
shopt -s extglob
rm -rf /usr/share/locale/!(en|en*|locale.alias)
rm -rf /usr/share/i18n/locales/!(en|en*|translit)

# Add Reboot at Midnight
echo '0  0     * * *   root    reboot' >> /etc/crontab

# Setup Watchdog to reboot if PI crashes
cat << END_TEXT > /etc/watchdog.conf
max-load-1 = 24
min-memory = 1
watchdog-device = /dev/watchdog
watchdog-timeout=15
END_TEXT

sed -i 's/default.target/multi-user.target/g' /lib/systemd/system/watchdog.service
sed -i 's/#RuntimeWatchdogSec=0/RuntimeWatchdogSec=10/g' /etc/systemd/system.conf
sed -i 's/#ShutdownWatchdog/ShutdownWatchdog/g' /etc/systemd/system.conf

# Fix for Exterprise WLAN connection
sed -i 's/nl80211,wext/wext,nl80211/g' /lib/systemd/system/wpa_supplicant@.service
sed -i 's/nl80211,wext/wext,nl80211/g' /lib/dhcpcd/dhcpcd-hooks/10-wpa_supplicant

# Restore init_resize
mkdir -p /usr/lib/raspi-config/
cp /root/init_resize.sh /usr/lib/raspi-config/