kind: Template
apiVersion: v1
metadata:
  name: appointment-chained-build
  annotations:
    description: ""
    tags: appointment,python
    iconClass: icon-python
labels:
  template: python
parameters:
  - name: SOURCE_REPOSITORY_URL
    displayName: Git Repository URL
    description: The URL of the repository with your application source code.
    # TODO - Revert value here when merged into mrain branch.
    # value: https://github.com/bcgov/queue-management.git
    value: https://github.com/bcgov/queue-management.git
  - name: SOURCE_REPOSITORY_REF
    displayName: Git Reference
    description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
    value: master
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: appointment-frontend-build
      annotations:
        description: "Keeps track of changes in the application image"
      labels:
        app: appointment-frontend-build
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: appointment-frontend
      annotations:
        description: "Keeps track of changes in the application image"
      labels:
        app: appointment-frontend
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: appointment-npm-build
      labels:
        app: appointment-npm-build
    spec:
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${SOURCE_REPOSITORY_REF}"
        contextDir: appointment-frontend
        secrets:
          - secret:
              name: npm-config
            destinationDir: /tmp/npmrc/
      strategy:
        type: Source
        sourceStrategy:
          env:
          - name: NODE_ENV
            value: production
          - name: VUE_APP_PATH
            value: /
          - name: NPM_CONFIG_USERCONFIG
            value: /tmp/npmrc/.npmrc
          from:
            kind: ImageStreamTag
            namespace: openshift
            name: nodejs:10
      output:
        to:
          kind: ImageStreamTag
          name: appointment-frontend-build:latest
      resources:
        limits:
          cpu: "1"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 4Gi
      postCommit: {}
      nodeSelector:
      successfulBuildsHistoryLimit: 10
      failedBuildsHistoryLimit: 2
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: appointment-frontend
      labels:
        app: appointment-frontend
    spec:
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange
      runPolicy: Serial
      source:
        type: Dockerfile
        dockerfile: "FROM s2i-caddy\nCOPY dist /var/www/html/\nCOPY caddy/Caddyfile /etc/Caddyfile"
        images:
          - from:
              kind: ImageStreamTag
              name: appointment-frontend-build:latest
            paths:
              - sourcePath: "/opt/app-root/src/dist"
                destinationDir: "./"
              - sourcePath: "/opt/app-root/src/caddy"
                destinationDir: "./"
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: s2i-caddy:latest
      output:
        to:
          kind: ImageStreamTag
          name: appointment-frontend:latest
      resources: {}
      postCommit: {}
      nodeSelector:
      successfulBuildsHistoryLimit: 10
      failedBuildsHistoryLimit: 2