apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    app: ${NAME}
  name: ${NAME}-build
  annotations:
    description: ""
    tags: appointment,python
    iconClass: icon-python
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${OUTPUT_IMAGE_TAG}
      resources:
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
        requests:
          cpu: ${CPU_REQUEST}
          memory: ${MEMORY_REQUEST}
      runPolicy: Serial
      source:
        contextDir: ${SOURCE_CONTEXT_DIR}
        git:
          ref: ${GIT_REF}
          uri: ${GIT_REPO_URL}
        type: Git
      strategy:
        type: Docker
        dockerStrategy:
          "dockerfilePath": "${DOCKER_FILE_PATH}"
          pullSecret:
            name: artifactory-creds
      postCommit: { }
      nodeSelector:
      successfulBuildsHistoryLimit: 10
      failedBuildsHistoryLimit: 2
      triggers:
        - type: ConfigChange
parameters:
  - description: |
      The name assigned to all of the objects defined in this template.
      You should keep this as default unless your know what your doing.
    displayName: Name
    name: NAME
    required: true
    value: appointment-nginx-frontend
  - description: |
      The URL to your GIT repo, don't use the this default unless
      your just experimenting.
    displayName: Git Repo URL
    name: GIT_REPO_URL
    required: true
    value: https://github.com/bcgov/queue-management
  - description: The git reference or branch.
    displayName: Git Reference
    name: GIT_REF
    required: true
    value: master
  - description: The source context directory.
    displayName: Source Context Directory
    name: SOURCE_CONTEXT_DIR
    required: false
    value: appointment-frontend
  - description: The tag given to the built image.
    displayName: Output Image Tag
    name: OUTPUT_IMAGE_TAG
    required: true
    value: latest
  - description: The resources CPU limit (in cores) for this build.
    displayName: Resources CPU Limit
    name: CPU_LIMIT
    required: true
    value: "2"
  - description: The resources Memory limit (in Mi, Gi, etc) for this build.
    displayName: Resources Memory Limit
    name: MEMORY_LIMIT
    required: true
    value: 4Gi
  - description: The resources CPU request (in cores) for this build.
    displayName: Resources CPU Request
    name: CPU_REQUEST
    required: true
    value: "1"
  - description: The resources Memory request (in Mi, Gi, etc) for this build.
    displayName: Resources Memory Request
    name: MEMORY_REQUEST
    required: true
    value: 4Gi
  - description: The path and file of the docker file defining the build.
    displayName: DockferFile
    name: DOCKER_FILE_PATH
    required: true
    value: Dockerfile
