kind: Template
apiVersion: v1
metadata:
  name: feedback-api
  annotations:
    description: ""
    tags: queue-management,python
    iconClass: icon-python
labels:
  template: python
parameters:
  - name: S2I_NAMESPACE
    displayName: Namespace
    description: The OpenShift Namespace where the S2I ImageStream resides.
    value: openshift
  - name: SOURCE_REPOSITORY_URL
    displayName: Git Repository URL
    description: The URL of the repository with your application source code.
    value: https://github.com/bcgov/queue-management.git
  - name: SOURCE_REPOSITORY_REF
    displayName: Git Reference
    description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
  - name: BUILD_NAMESPACE
    value: ''
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: feedback-api
      annotations:
        description: "Keeps track of changes in the application image"
      labels:
        app: feedback-api
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: feedback-api
      labels:
        app: feedback-api
    spec:
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${SOURCE_REPOSITORY_REF}"
        contextDir: feedback-api
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            namespace: openshift
            name: python:latest
      output:
        to:
          kind: ImageStreamTag
          name: feedback-api:latest
      resources:
        limits:
          cpu: '1'
          memory: 8Gi
        requests:
          cpu: '1'
          memory: 4Gi
      postCommit: {}
      nodeSelector:
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 2
    status:
      lastVersion: 0