apiVersion: v1
kind: Template
labels:
  template: notifications-api
  app.kubernetes.io/part-of: TheQ
metadata:
  name: notifications-api
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: "Exposes and load balances the api pods"
      name: "${API_NAME}"
      labels:
        app: "${API_NAME}"
    spec:
      ports:
        - name: web
          port: 8080
          targetPort: 8080
      selector:
        app: "${API_NAME}"
  - apiVersion: v1
    kind: Route
    metadata:
      name: "${API_NAME}"
    spec:
      host: "${API_APPLICATION_DOMAIN}"
      path: /api
      to:
        kind: Service
        name: "${API_NAME}"
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        description: "Defines how to deploy the application server"
        template.alpha.openshift.io/wait-for-ready: "true"
      name: "${API_NAME}"
    spec:
      replicas: 2
      selector:
        name: ${API_NAME}
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 120
          maxSurge: 2
          maxUnavailable: 1
        resources:
           limits:
             cpu: 100m
             memory: 200Mi
           requests:
             cpu: 50m
             memory: 100Mi
        activeDeadlineSeconds: 3600
      template:
        metadata:
          labels:
            app: "${API_NAME}"
            name: "${API_NAME}"
        spec:
          containers:
            - name: "${API_NAME}"
              image: " "
              env:
                - name: APP_CONFIG
                  value: gunicorn_config.py
                - name: FLASK_ENV
                  value: "${FLASK_ENV}"
                - name: APP_MODULE
                  value: wsgi
                - name: SECRET_KEY
                  value: "${SECRET_KEY}"
                - name: SERVER_NAME
                  value: "${API_APPLICATION_DOMAIN}"
                - name: CACHE_DEFAULT_TIMEOUT
                  value: "${CACHE_DEFAULT_TIMEOUT}"
                - name: SMS_USE_GC_NOTIFY
                  value: "true"
                - name: GC_NOTIFY_API_KEY
                  value: "${GC_NOTIFY_API_KEY}"
                - name: GC_NOTIFY_API_BASE_URL
                  value: "${GC_NOTIFY_API_BASE_URL}"
                - name: GC_NOTIFY_SMS_TEMPLATE_ID
                  value: "${GC_NOTIFY_SMS_TEMPLATE_ID}"
                - name: SMS_APPOINTMENT_APP_URL
                  value: "${SMS_APPOINTMENT_APP_URL}"
                - name: APPOINTMENT_APP_URL
                  value: "${APPOINTMENT_APP_URL}"
                - name: PRINT_ENABLE
                  value: "false"
                - name: LOG_BASIC
                  value: WARNING
                - name: LOG_ROOT
                  value: WARNING
                - name: SMS_REMINDER_TEMPLATE
                  value: "${SMS_REMINDER_TEMPLATE}"
                - name: JWT_OIDC_WELL_KNOWN_CONFIG
                  value: "${JWT_OIDC_WELL_KNOWN_CONFIG}"
                - name: JWT_OIDC_ALGORITHMS
                  value: "${JWT_OIDC_ALGORITHMS}"
                - name: JWT_OIDC_AUDIENCE
                  value: "${JWT_OIDC_AUDIENCE}"
                - name: JWT_OIDC_CLIENT_SECRET
                  value: "${JWT_OIDC_CLIENT_SECRET}"
                - name: CHES_POST_EMAIL_ENDPOINT
                  valueFrom:
                    configMapKeyRef:
                      name: appointment-reminder-prod-config
                      key: CHES_POST_EMAIL_ENDPOINT
                - name: CHES_SSO_CLIENT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: appointment-reminder-prod-config
                      key: CHES_SSO_CLIENT_ID
                - name: CHES_SSO_CLIENT_SECRET
                  valueFrom:
                    configMapKeyRef:
                      name: appointment-reminder-prod-config
                      key: CHES_SSO_CLIENT_SECRET
                - name: CHES_SSO_TOKEN_URL
                  valueFrom:
                    configMapKeyRef:
                      name: appointment-reminder-prod-config
                      key: CHES_SSO_TOKEN_URL
                - name: SMS_CHECKIN_CONFIRMATION_TEMPLATE
                  value: >-
                    Thank you for saving your spot in line with Service BC! We will
                    be with you shortly. To see your place in line, follow this
                    link, you are ticket {ticket_number}: {url}
              ports:
                - containerPort: 8080
              readinessProbe:
                httpGet:
                  path: /api/v1/healthz
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              terminationMessagePath: /dev/termination-log
              name: notifications-api
              livenessProbe:
                httpGet:
                  path: /api/v1/readyz
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              terminationMessagePath: "/dev/termination-log"
              terminationMessagePolicy: File
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 400m
                  memory: 400Mi
                limits:
                  cpu: '1'
                  memory: 600Mi
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: name
                        operator: In
                        values:
                          - "${API_NAME}"
                  topologyKey: kubernetes.io/hostname
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - "${API_NAME}"
            from:
              kind: ImageStreamTag
              namespace: "${TOOLS_WORKSPACE}"
              name: "${API_NAME}:${API_IMAGE_TAG}"
parameters:
  - name: API_NAME
    displayName: Name
    description: "Name of the flask application"
    required: true
    value: "notifications-api"
  - name: API_APPLICATION_DOMAIN
    description: "The exposed hostname that will route to the Flask service"
    required: true
    value: ""
  - name: FLASK_ENV
    description: "The configuration object that should be loaded for this deployment."
    required: true
    value: "production"
  - name: API_IMAGE_TAG
    description: "The tag to use when deploying"
    required: true
  - name: TOOLS_WORKSPACE
    description: "IMAGE STREAM WORKSPACE LOCATION"
    required: true
    value: ""
  - name: SECRET_KEY
    description: "Key required for Flask"
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{16}"
  - name: SMS_USE_GC_NOTIFY
    description: "Flag to use GC Notify"
    required: true
    value: "true"
  - name: GC_NOTIFY_API_KEY
    description: "GC Notify API Key"
    required: true
  - name: GC_NOTIFY_API_BASE_URL
    description: "GC Notify API Base URL"
    required: true
    value: "https://api.notification.canada.ca/"
  - name: GC_NOTIFY_SMS_TEMPLATE_ID
    description: "GC Notify SM Template ID"
    required: true
  - name: APPOINTMENT_APP_URL
    description: "Appointment App URL"
    required: true
    value: "http://tinyurl.com/o9g8bxey"
  - name: SMS_APPOINTMENT_APP_URL
    description: "Appointment Url to provide in sms"
    required: true
    value: "http://tinyurl.com/o9g8bxey"
  - name: SMS_REMINDER_TEMPLATE
    description: "SMS Template text"
    required: true
    value: "REMINDER: You have an appointment with Service BC {location} on {date_time}. To cancel or change, visit {app_url} or call {office_telephone}"
  - name: JWT_OIDC_WELL_KNOWN_CONFIG
    description: "Well known config URL for the keycloak realm "
    required: true
    value: ""
  - name: JWT_OIDC_ALGORITHMS
    description: "OIDC Algorithm"
    required: false
    value: "RS256"
  - name: JWT_OIDC_AUDIENCE
    description: "OIDC Audience"
    required: true
    value: "notifications-api"
  - name: JWT_OIDC_CLIENT_SECRET
    description: "OIDC Client secret"
    required: false
    value: ""
