kind: Template
apiVersion: v1
metadata:
  name: percona
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: percona-passwords
      annotations:
        template.openshift.io/base64-expose-root: "{.data['root']}"
        template.openshift.io/base64-expose-clustercheck: "{.data['clustercheck']}"
        template.openshift.io/base64-expose-monitor: "{.data['monitor']}"
        template.openshift.io/base64-expose-xtrabackup: "{.data['xtrabackup']}"
        template.openshift.io/expose-mysql_user: "{.data['mysql_user']}"
        template.openshift.io/expose-mysql_password: "{.data['mysql_password']}"
        template.openshift.io/expose-mysql_database: "{.data['mysql_database']}"
    type: Opaque
    stringData:
      root: "${MYSQL_ROOT_PASSWORD}"
      clustercheck: "${MYSQL_CLUSTER_CHECK_PASSWORD}"
      monitor: "${MONITOR_PASSWORD}"
      xtrabackup: "${XTRABACKUP_PASSWORD}"
      mysql_user: "${MYSQL_USER}"
      mysql_password: "${MYSQL_PASSWORD}"
      mysql_database: "${MYSQL_DATABASE}"
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: percona
      labels:
        app: percona
    data:
      extra.cnf: |
        [mysqld]
        innodb_buffer_pool_size=1G
        innodb_log_file_size=256M
        innodb_flush_method=O_DIRECT
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
      name: percona
      labels:
        app: percona
    spec:
      ports:
        - port: 3306
          name: mysql-port
      clusterIP: None
      selector:
        app: percona
  - apiVersion: apps/v1beta1
    kind: StatefulSet
    metadata:
      name: percona
    spec:
      selector:
        matchLabels:
          app: percona
      serviceName: "percona"
      replicas: 3
      template:
        metadata:
          labels:
            app: percona
            name: percona
        spec:
          containers:
            - name: mysql
              image: perconalab/pxc-openshift:master
              imagePullPolicy: Always
              ports:
                - containerPort: 3306
                  name: mysql
                - containerPort: 4444
                  name: sst
                - containerPort: 4567
                  name: replication
                - containerPort: 4568
                  name: ist
              readinessProbe:
                exec:
                  command:
                    - /usr/bin/clustercheck.sh
                initialDelaySeconds: 15
                timeoutSeconds: 15
                periodSeconds: 30
                failureThreshold: 5
              livenessProbe:
                exec:
                  command:
                    - /usr/bin/clustercheck.sh
                initialDelaySeconds: 300
                timeoutSeconds: 5
                periodSeconds: 10
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  cpu: 500m
                  memory: 2Gi
              volumeMounts:
                - name: datadir
                  mountPath: /var/lib/mysql
                  subPath: data
                - name: config-volume
                  mountPath: /etc/mysql/conf.d/
              env:
                - name: MYSQL_FORCE_INIT
                  value: "1"
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: percona-passwords
                      key: root
                - name: CLUSTERCHECK_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: percona-passwords
                      key: clustercheck
                - name: MONITOR_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: percona-passwords
                      key: monitor
                - name: XTRABACKUP_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: xtrabackup
                      name: percona-passwords
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: mysql_user
                      name: percona-passwords
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: mysql_password
                      name: percona-passwords
                - name: MYSQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: mysql_database
                      name: percona-passwords
          volumes:
            - name: config-volume
              configMap:
                name: percona
                optional: true
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: name
                        operator: In
                        values:
                          - percona
                  topologyKey: kubernetes.io/hostname
      volumeClaimTemplates:
        - metadata:
            name: datadir
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
parameters:
  - description: The root password for percona.
    name: MYSQL_ROOT_PASSWORD
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{16}"
  - description: The password used for clusterchecking.
    name: MYSQL_CLUSTER_CHECK_PASSWORD
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{16}"
  - description: The password used for monitoring.
    name: MONITOR_PASSWORD
    required: true
    value: "monitor"
  - description: The password used for xtrabackup.
    name: XTRABACKUP_PASSWORD
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{16}"
  - description: The password used for xtrabackup.
    name: MYSQL_USER
    required: true
    generate: expression
    from: "user[a-zA-Z0-9]{3}"
  - description: The password used for xtrabackup.
    name: MYSQL_PASSWORD
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{16}"
  - description: The password used for xtrabackup.
    name: MYSQL_DATABASE
    required: true
    value: "queue_management"
