apiVersion: v1
kind: Template
labels:
  template: queue-management-frontend
metadata:
  name: queue-management-frontend
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: frontend-videos
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: "1Gi"
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: keycloak.json
      labels:
        app: queue-management-frontend
    data:
      keycloak.json: |
        {
          "realm": "<realm>",
          "auth-server-url": "https://<keycloak server>/auth",
          "ssl-required": "external",
          "resource": "<keycloak client>",
          "credentials": {
            "secret": "<keycloak client secret>"
          }
        }
  - apiVersion: v1
    kind: Service
    metadata:
      name: "${NAME}"
      labels:
        app: "${NAME}"
    spec:
      ports:
        - name: web
          protocol: TCP
          port: 2015
          targetPort: 2015
      selector:
        app: "${NAME}"
      type: ClusterIP
      sessionAffinity: None
  - apiVersion: v1
    kind: Route
    metadata:
      name: "${NAME}"
    spec:
      host: "${APPLICATION_DOMAIN}"
      to:
        kind: Service
        name: "${NAME}"
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
  - kind: DeploymentConfig
    metadata:
      name: "${NAME}"
      labels:
        app: queue-management
    spec:
      replicas: 2
      selector:
        app: "${NAME}"
        deploymentconfig: "${NAME}"
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 60
          maxSurge: 2
          maxUnavailable: 1
        resources: {}
        activeDeadlineSeconds: 3600
      template:
        metadata:
          labels:
            app: "${NAME}"
            name: "${NAME}"
        spec:
          containers:
            - name: "${NAME}"
              image: " "
              args:
                - "/tmp/scripts/run"
              ports:
                - containerPort: 2015
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 3
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 2015
                timeoutSeconds: 3
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 3
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 2015
                timeoutSeconds: 3
              volumeMounts:
                - mountPath: /var/www/html/static/videos
                  name: frontend-videos
                  readOnly: false
              terminationMessagePath: "/dev/termination-log"
              terminationMessagePolicy: File
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 50m
                  memory: 256Mi
                limits:
                  cpu: 100m
                  memory: 512Mi
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
          volumes:
            - configMap:
                defaultMode: 420
                name: keycloak.json
              name: keycloak.json
            - name: frontend-videos
              persistentVolumeClaim:
                claimName: frontend-videos
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: name
                        operator: In
                        values:
                          - "${NAME}"
                  topologyKey: kubernetes.io/hostname
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - "${NAME}"
            from:
              kind: ImageStreamTag
              namespace: ${TOOLS_WORKSPACE}
              name: "${NAME}:${IMAGE_TAG}"
parameters:
  - name: NAME
    displayName: Name
    description: The suffix for all created objects
    required: false
    value: queue-management-frontend
  - name: APPLICATION_DOMAIN
    description: "The exposed hostname that will route to the Vue application"
    value: ""
  - name: IMAGE_TAG
    description: The image tag to pull for the deployment.
    required: true
    value: dev
  - name: TOOLS_WORKSPACE
    description: The Location for your image streams (Tools Workspace)
    required: true
