kind: Template
apiVersion: v1
metadata:
  name: 'notifications-api-build-template'
  annotations:
    description: Build template for notifications-api.
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: notifications-api
      annotations:
        description: "Keeps track of changes in the application image"
      labels:
        app: notifications-api
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: notifications-api
      labels:
        app: notifications-api
    spec:
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${SOURCE_REPOSITORY_REF}"
        contextDir: notifications-api
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: DockerImage
            name: 'registry.access.redhat.com/ubi8/python-38:latest'
      output:
        to:
          kind: ImageStreamTag
          name: notifications-api:latest
      resources: {}
      postCommit: {}
      nodeSelector:
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 2
    status:
      lastVersion: 0
parameters:
  - name: SOURCE_REPOSITORY_URL
    displayName: Git Repository URL
    description: The URL of the repository with your application source code.
    value: https://github.com/bcgov/queue-management.git
  - name: SOURCE_REPOSITORY_REF
    displayName: Git Reference
    description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
    value: master
