#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

set -e

DOCKER_IMAGE_NAME=bcgov/smartboard-shrink-image

$DIR/docker-build

show_usage() {
  echo "Usage:"
  echo "$0 raspbian-image-to-shrink.img"
}

if [ "$#" -ne 1 ]; then
  echo "ERROR: 1 parameter required."
  show_usage
  exit 1
fi

INPUT_IMAGE=$1

mkdir -p output

if [ ! -f "$INPUT_IMAGE" ]; then
  echo "ERROR: File passed as input is not accessible."
  show_usage
  exit 1
fi

VOLUME=$(dirname $(realpath $1))
IMAGE_NAME=$(basename $1)
OUTPUT_DIR=$(realpath output)

docker run \
       -ti \
       --privileged=true \
       --mount type=bind,source=$VOLUME,target=/image \
       --mount type=bind,source=$OUTPUT_DIR,target=/output \
       $DOCKER_IMAGE_NAME $IMAGE_NAME

# Replace the tmp image with the shrunk image
mv output/$IMAGE_NAME.tmp output/$IMAGE_NAME

printf "Shrunk Image:\n\t$(realpath output/$IMAGE_NAME)\n"
