# Copyright 2022 Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

version: '3.7'

services:
  # The container that contains all the code in the repository, plus the
  # installations of Python requirements and Node packages.
  app:
    build:
      args:
        # Update 'VARIANT' to pick a version of Python: 3, 3.10, 3.9, 3.8,
        # 3.7, 3.6. Append -bullseye or -buster to pin to an OS version. Use
        # -bullseye variants on local arm64/Apple Silicon.
        #
        # Note: Tying ourselves to Python 3.8.8 to match the runtime version
        # means that we are tied to old vscode images. We should consider an
        # update to the runtime version. The list of versions available is at
        # https://hub.docker.com/_/microsoft-vscode-devcontainers
        # https://mcr.microsoft.com/v2/vscode/devcontainers/python/tags/list
        VARIANT: '0.201.2-3.8'

        # Node.js version to install
        NODE_VERSION: '14.17.5'

      context: '..'

      dockerfile: '.devcontainer/Dockerfile'

    # Overrides default command so things don't shut down after the process
    # ends.
    command: 'sleep infinity'

    environment:
      # For container "db".
      DATABASE_NAME: 'postgres'
      DATABASE_PASSWORD: 'postgres'

      # For container "x11" used by Cypress.
      DISPLAY: ':14'
      LIBGL_ALWAYS_INDIRECT: '0'

    init: true

    # Runs app on the same network as the database container, allows
    # "forwardPorts" in devcontainer.json function.
    network_mode: 'service:db'

    volumes:
      - 'x11:/tmp/.X11-unix:rw'
      - '..:/workspace:cached'

  # Run PostgreSQL as the database used by the API. Keep the version in sync
  # with what is used in the runtime deployments.
  db:
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'

    image: 'postgres:13.4'

    restart: 'unless-stopped'

    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

#  keycloak:
#    environment:
#      KEYCLOAK_PASSWORD: 'admin'
#      KEYCLOAK_USER: 'admin'
#
#    image: 'jboss/keycloak:9.0.3'
#
#    ports:
#      - '8085:8080'

  # Display X clients (like Cypress) on an X server that uses Xpra to forward
  # the display. Set the XPRA_PASSWORD password below and use a browser outside
  # Docker to view the clients:
  #    http://localhost:10000/index.html?encoding=rgb32&password=XPRA_PASSWORD
  x11:
    environment:
      DISPLAY: ':14'
      MODE: 'tcp'
      XPRA_HTML: 'yes'
      XPRA_PASSWORD: 'password'

    image: 'jare/x11-bridge'

    ports:
      - '10000:10000'

    restart: 'always'

    volumes:
      - 'x11:/tmp/.X11-unix:rw'

volumes:
  postgres-data:
  x11:
