#! /bin/bash

mount / -o remount,rw

sed -i 's/IPV6=yes/IPV6=no/g' /etc/default/ufw
systemctl daemon-reload
ufw default deny incoming 
ufw default allow outgoing
ufw allow 443
ufw allow `cat /var/sshd_port`
ufw allow ntp 
ufw --force enable

mount / -o remount,ro
exit 0