#! /bin/bash

# NOTE: All the content of the config files must be contained in this
# script as it will be loaded before the new FS will be available.

cat << END_TEXT > /uboot/config.txt
disable_splash=1

hdmi_force_hotplug=1

# To remove the undervoltage warning:
avoid_warnings=1

# Increase GPU Memory
gpu_mem_1024=64

#enable GPU Driver
dtoverlay=vc4-kms-v3d
dtparam=watchdog=on

END_TEXT

cat << END_TEXT > /uboot/cmdline.txt
dwc_otg.lpm_enable=0 console=serial0,115200 root=\${mender_kernel_root} rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait logo.nologo
END_TEXT
exit 0
