apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: github-actions
objects:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: github-actions
  rules:
  - verbs:
      - get
      - update
    apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
      - imagestreams/layers
  - verbs:
      - create
    apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: github-actions
  subjects:
    - kind: ServiceAccount
      name: github-actions
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: github-actions
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: github-actions
