"""online_flag

Revision ID: 01e9a0399784
Revises: 2913f24ec7ad
Create Date: 2020-05-01 23:59:12.129846

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '01e9a0399784'
down_revision = '2913f24ec7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('online_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'online_flag')
    # ### end Alembic commands ###
