"""empty message

Revision ID: 05301cda7812
Revises: a05659940088
Create Date: 2020-01-12 17:00:38.148200

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '05301cda7812'
down_revision = 'a05659940088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam', 'exam_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam', 'exam_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
