"""empty message

Revision ID: 06e914da9675
Revises: 44c03a3c8a83
Create Date: 2019-12-01 17:43:02.346955

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '06e914da9675'
down_revision = '44c03a3c8a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('payee_email', sa.String(length=50), nullable=True))
    op.add_column('exam', sa.Column('payee_ind', sa.Integer(), nullable=True))
    op.add_column('exam', sa.Column('payee_name', sa.String(length=50), nullable=True))
    op.add_column('exam', sa.Column('payee_phone', sa.String(length=50), nullable=True))
    op.add_column('exam', sa.Column('receipt', sa.String(length=50), nullable=True))
    op.add_column('exam', sa.Column('receipt_sent_ind', sa.Integer(), nullable=True))
    op.add_column('exam', sa.Column('sbc_managed_ind', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'sbc_managed_ind')
    op.drop_column('exam', 'receipt_sent_ind')
    op.drop_column('exam', 'receipt')
    op.drop_column('exam', 'payee_phone')
    op.drop_column('exam', 'payee_name')
    op.drop_column('exam', 'payee_ind')
    op.drop_column('exam', 'payee_email')
    # ### end Alembic commands ###
