"""empty message

Revision ID: 06f4ae2201d8
Revises: cbf81e4d5757
Create Date: 2019-03-28 10:28:15.265984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06f4ae2201d8'
down_revision = 'cbf81e4d5757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('exam_returned_date', sa.DateTime(), nullable=True))
    op.add_column('exam', sa.Column('exam_written_ind', sa.Integer(), nullable=False))
    op.drop_column('exam', 'exam_returned_ind')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('exam_returned_ind', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('exam', 'exam_written_ind')
    op.drop_column('exam', 'exam_returned_date')
    # ### end Alembic commands ###
