"""empty message

Revision ID: 0a174479323a
Revises: eee726e68b4a
Create Date: 2019-01-04 12:29:12.107753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a174479323a'
down_revision = 'eee726e68b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizen', 'service_count')
    op.add_column('servicereq', sa.Column('sr_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicereq', 'sr_number')
    op.add_column('citizen', sa.Column('service_count', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
