"""empty message

Revision ID: 0b452e9fb67c
Revises: b73622264ca0
Create Date: 2020-08-26 11:01:56.203716

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '0b452e9fb67c'
down_revision = 'b73622264ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csr', 'liaison_designate')
    op.drop_column('csr', 'ita_designate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csr', sa.Column('ita_designate', sa.INTEGER(), autoincrement=False, nullable=False, server_default="0"))
    op.add_column('csr', sa.Column('liaison_designate', sa.INTEGER(), autoincrement=False, nullable=False, server_default="0"))
    # ### end Alembic commands ###
