"""empty message

Revision ID: 0e0a38cb41aa
Revises: 22d89f09b430
Create Date: 2019-03-01 09:22:38.571336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0a38cb41aa'
down_revision = '22d89f09b430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csr', sa.Column('finance_designate', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csr', 'finance_designate')
    # ### end Alembic commands ###
