"""empty message

Revision ID: 1171a9129db4
Revises: 92cd814a5c05
Create Date: 2019-10-28 12:38:09.544823

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '1171a9129db4'
down_revision = '92cd814a5c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('recurring_uuid', sa.String(length=255), nullable=True))
    op.add_column('booking', sa.Column('recurring_uuid', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'recurring_uuid')
    op.drop_column('booking', 'recurring_uuid')
    # ### end Alembic commands ###
