"""empty message

Revision ID: 11d6429f518c
Revises: f6234fc92d1c
Create Date: 2019-02-06 10:42:05.090646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d6429f518c'
down_revision = 'f6234fc92d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csr', sa.Column('ita_designate', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csr', 'ita_designate')
    # ### end Alembic commands ###
