"""add_telephone_to_office

Revision ID: 13e4908529d2
Revises: d2bbfaeeb7d9
Create Date: 2020-04-29 19:08:19.651648

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '13e4908529d2'
down_revision = 'd2bbfaeeb7d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office', sa.Column('telephone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('office', 'telephone')
    # ### end Alembic commands ###
