"""empty message

Revision ID: 13f777964cf9
Revises: 62686ac6eefc
Create Date: 2021-03-23 12:08:19.344495

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '13f777964cf9'
down_revision = '62686ac6eefc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen', sa.Column('automatic_reminder_flag', sa.Integer(), nullable=True))
    op.add_column('citizen', sa.Column('notification_email', sa.String(length=100), nullable=True))
    op.add_column('citizen', sa.Column('notification_phone', sa.String(length=100), nullable=True))
    op.add_column('citizen', sa.Column('notification_sent_time', sa.DateTime(), nullable=True))
    op.add_column('citizen', sa.Column('reminder_flag', sa.Integer(), nullable=True))
    op.add_column('citizen', sa.Column('walkin_unique_id', sa.String(length=500), nullable=True))
    op.add_column('office', sa.Column('automatic_reminder_at', sa.Integer(), nullable=True))
    op.add_column('office', sa.Column('check_in_notification', sa.Integer(), nullable=True))
    op.add_column('office', sa.Column('check_in_reminder_msg', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('office', 'check_in_reminder_msg')
    op.drop_column('office', 'check_in_notification')
    op.drop_column('office', 'automatic_reminder_at')
    op.drop_column('citizen', 'walkin_unique_id')
    op.drop_column('citizen', 'reminder_flag')
    op.drop_column('citizen', 'notification_sent_time')
    op.drop_column('citizen', 'notification_phone')
    op.drop_column('citizen', 'notification_email')
    op.drop_column('citizen', 'automatic_reminder_flag')
    # ### end Alembic commands ###
