"""empty message

Revision ID: 198b2c9110b9
Revises: c25c4ee67df6
Create Date: 2020-11-27 10:21:22.200304

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '198b2c9110b9'
down_revision = 'c25c4ee67df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('css_colour', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'css_colour')
    # ### end Alembic commands ###
