"""empty message

Revision ID: 2913f24ec7ad
Revises: 13e4908529d2
Create Date: 2020-04-30 19:08:24.257797

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2913f24ec7ad'
down_revision = '13e4908529d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # days.create(op.get_bind())
    # Delete all records from the table
    op.execute('delete from timeslot')
    op.add_column('office', sa.Column('disable_online_appointment', sa.Boolean(), nullable=True))
    op.drop_column('timeslot', 'day_of_week')
    op.add_column('timeslot', sa.Column('day_of_week', postgresql.ARRAY(sa.VARCHAR()), nullable=False))
    op.alter_column('timeslot', 'day_of_week',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('office', 'disable_online_appointment')

    # ### end Alembic commands ###
