"""SBCQ-307 Add new columns to Office

Revision ID: 297f8e37fee4
Revises: 8b6c67545310
Create Date: 2024-12-16 19:33:04.875950

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '297f8e37fee4'
down_revision = '8b6c67545310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office', sa.Column('core_service_partners', sa.String(), nullable=True))
    op.add_column('office', sa.Column('service_model', sa.String(), server_default='Reception', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('office', 'service_model')
    op.drop_column('office', 'core_service_partners')
    # ### end Alembic commands ###
