"""empty message

Revision ID: 2fc4029b8645
Revises: 302354e5ba09
Create Date: 2018-12-14 09:40:16.195268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2fc4029b8645'
down_revision = '302354e5ba09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam', 'examinee_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('exam', 'invigilator_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('exam', 'number_of_students',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('exam', 'session_number',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('exam_ibfk_5', 'exam', type_='foreignkey')
    op.drop_column('exam', 'room_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('room_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('exam_ibfk_5', 'exam', 'room', ['room_id'], ['room_id'])
    op.alter_column('exam', 'session_number',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('exam', 'number_of_students',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('exam', 'invigilator_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('exam', 'examinee_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
