"""empty message

Revision ID: 34df859d1d05
Revises: 71486b5dce97
Create Date: 2020-12-08 12:05:35.868123

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '34df859d1d05'
down_revision = '71486b5dce97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office', sa.Column('soonest_appointment', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('office', 'soonest_appointment')
    # ### end Alembic commands ###
