"""empty message

Revision ID: 3a98e5395000
Revises: 6a7246416d91
Create Date: 2019-04-09 16:55:34.963912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a98e5395000'
down_revision = '6a7246416d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('office_back_office_list',
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['office.office_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('office_id', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('office_back_office_list')
    # ### end Alembic commands ###
