"""empty message

Revision ID: 3f8e6c8468f1
Revises: 223526cbd142
Create Date: 2019-01-28 09:23:31.363877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f8e6c8468f1'
down_revision = '223526cbd142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('office_id', sa.Integer(), nullable=False))
    op.alter_column('booking', 'room_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'booking', 'office', ['office_id'], ['office_id'])
    op.alter_column('exam', 'offsite_location',
                    existing_type=sa.VARCHAR(length=50),
                    type_=sa.VARCHAR(length=255))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.alter_column('booking', 'room_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('booking', 'office_id')
    # ### end Alembic commands ###
