"""sbcq253_service_description

Revision ID: 42ee86bb6d2e
Revises: 20cc7ab888e9
Create Date: 2024-10-09 16:42:00.383166

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '42ee86bb6d2e'
down_revision = '0b7af23605fb'
branch_labels = None
depends_on = None


def upgrade():

    # Generated SQL commands for upgrade
    op.execute("""UPDATE service SET service_desc = 'F&W - hunter needing FWID only or update to account (do not use this code if looking up is part of hunting license or LEH issuance)' WHERE service_id = '61';""")
    op.execute("""UPDATE service SET service_desc = 'MSP- SC686, SC1089, SC1278  - Outstanding MSP payments, International Student Health Fee.' WHERE service_id = '109';""")
    op.execute("""UPDATE service SET service_desc = 'RTB - Assisting citizens with online applications at CATs.  Back office duties such as management of Abandoned files.  Other misc. services' WHERE service_id = '142';""")
    op.execute("""UPDATE service SET service_desc = 'BC Online - All searches using BC Online i.e. BC Assessment/Man Homes/Company & Society searches/PPR Lien search etc.' WHERE service_id = '151';""")
    op.execute("""UPDATE service SET service_desc = 'ITA Invigilation - one-off;  Pre/During/Post - All work involved from receiving the exam, to mailing the completed exam and materials to ITA and BC Mail.' WHERE service_id = '160';""")
    op.execute("""UPDATE service SET service_desc = 'ITA - Checking exam materials, copying or scanning exam, mailing etc.' WHERE service_id = '163';""")
    op.execute("""UPDATE service SET service_desc = 'ITA - Can include PRE, DURING and/or POST for offsite invigilation.' WHERE service_id = '166';""")
    op.execute("""UPDATE service SET service_desc = 'ITA - Checking for expired exams, contacting ITA program, mailing back ITA etc.' WHERE service_id = '169';""")
    op.execute("""UPDATE service SET service_desc = 'Exams-Providing Information about all exams, invigilation of other exams such as angling/guide outfitter exam, veterinary exam, bulk tank milk grader exam, ITA card replacement etc.' WHERE service_id = '172';""")
    op.execute("""UPDATE service SET service_desc = 'PEST Invigilation - one-off Pre/During/Post - All work involved from scheduling the candidate, to uploading the completed materials. ' WHERE service_id = '175';""")
    op.execute("""UPDATE service SET service_desc = 'PEST-Can include PRE, DURING and/or POST for offsite invigilation.' WHERE service_id = '178';""")
    op.execute("""UPDATE service SET service_desc = 'Notary - All Notary duties.' WHERE service_id = '217';""")
    op.execute("""UPDATE service SET service_desc = 'Providing Information for misc. programs, applications such as gaming, photocopies, faxes, misc. forms, Front Counter BC, Human Rights Tribunal, Public Trustee, Legal Aid, bereavement checklist, foreign pension, Safer, HAFI, BC Housing, Seafood Licencing etc.   Payments such as ministry collections and student loans (e.g., Service Code 1278/Revenue Services of BC (RSBC), MCFD SC1459, , Mineral Tax., Mineral Inspection, , Bridge Toll etc.' WHERE service_id = '220';""")
    op.execute("""UPDATE service SET service_desc = 'Redirect - Directing citizen to the Office Phone to self serve' WHERE service_id = '232';""")
    op.execute("""UPDATE service SET service_desc = 'Batching' WHERE service_id = '247';""")
    op.execute("""UPDATE service SET service_desc = 'ICBC - Knowledge Test Set up/Result: KT - Either put it on hold or end it after the test set up. When client returns, you either resume or create a new one.' WHERE service_id = '313';""")
    op.execute("""UPDATE service SET service_desc = 'ICBC - Road Test Set up/Result: RT -  Either put it on hold or end it after the test set up. When client returns, you either resume or create a new one.' WHERE service_id = '316';""")
    op.execute("""UPDATE service SET service_desc = 'ICBC Auto - Commission Tracking' WHERE service_id = '340';""")
    op.execute("""UPDATE service SET service_desc = 'ICBC Auto - Cancel Policy' WHERE service_id = '352';""")
    op.execute("""UPDATE service SET service_desc = 'MCFD - Contract agreements, Coding blocks, Purchase documents, Petty Cash (holder of) and reconciliation,  Respite/Relief forms,' WHERE service_id = '385';""")
    op.execute("""UPDATE service SET service_desc = 'SDPR 3rd Party - Assisting individual clients with imprest cheque pick up, cancelling and mailing per SDPR direction. This includes client tracking and signatures (if applicable).' WHERE service_id = '412';""")
    op.execute("""UPDATE service SET service_desc = 'SDPR POC - weekly reports to SDPR, mail sorting if applicable (not cheques), monthly batching mail out to SDPR etc.' WHERE service_id = '418';""")
    op.execute("""UPDATE service SET service_desc = 'SDPR 3rd Party - Emptying stub drop box, scanning stubs, preparing mail.' WHERE service_id = '463';""")
    op.execute("""UPDATE service SET service_desc = 'Assisting citizen with SBC App. guidance/access issues.' WHERE service_id = '490';""")
    op.execute("""UPDATE service SET service_desc = 'SC 1664 - Completing a Worker Attestation, Taking $100 payment, Witnessing signature, coping ID, scanning to LCRB etc.' WHERE service_id = '510';""")
    op.execute("""UPDATE service SET service_desc = 'Client Liaison/Program Specialist for ITA; Includes Job Aid work, CSR related meetings, document creation, field assistance, etc.', email_paragraph = NULL WHERE service_id = '533';""")
    op.execute("""UPDATE service SET service_desc = 'SC800, Speculation Tax, SVT, taking a vacancy SVT  payment.' WHERE service_id = '575';""")
    op.execute("""UPDATE service SET service_desc = 'Professional Excellence Team Members only; attend Training Team meetings, communication, developing training material, TIMS data entry, training budgets, etc.' WHERE service_id = '601';""")
    op.execute("""UPDATE service SET service_desc = 'RTB - Preparing hearing packages for pick up, submitting applications for amendment' WHERE service_id = '606';""")
    op.execute("""UPDATE service SET service_desc = 'RTB - Application for Review, Correction/Clarification' WHERE service_id = '609';""")
    op.execute("""UPDATE service SET service_desc = 'RTB - Providing Information for general program and application processes, RTB contact info, printing and providing forms' WHERE service_id = '617';""")
    op.execute("""UPDATE service SET service_desc = 'MSP- Providing/reviewing applications, forwarding to HIBC.' WHERE service_id = '618';""")
    op.execute("""UPDATE service SET service_desc = 'F&W - Royalty Payments, Any BACK OFFICE work issuing licences/creating FWIDs for Guides  (i.e.  bulk drop off  licence requests).  Track FRONT COUNTER  services as Hunting - Non-Resident' WHERE service_id = '619';""")
    op.execute("""UPDATE service SET service_desc = 'All office cleaning and sanitizing correlated to staff and citizen safety during the COVID pandemic.' WHERE service_id = '652';""")
    op.execute("""UPDATE service SET service_desc = 'All office cleaning and sanitizing correlated to staff and citizen safety during the COVID pandemic.' WHERE service_id = '653';""")
    op.execute("""UPDATE service SET service_desc = 'All calls and reporting correlated to the COVID Traveler project.  TRACK EACH CALL separately.' WHERE service_id = '654';""")
    op.execute("""UPDATE service SET service_desc = 'All Tier 2 support calls and reporting correlated to the COVID Traveler project.  TRACK EACH CALL separately.' WHERE service_id = '655';""")
    op.execute("""UPDATE service SET service_desc = 'Online ID Verification process (includes verifying, rejecting, and contacting/forwarding to Tier 2 for assistance or completion).  TRACK EACH VERIFICATION separately.' WHERE service_id = '656';""")
    op.execute("""UPDATE service SET service_desc = 'Traveler Project - Calls to Temporary Foreign Workers ONLY.  TRACK EACH CALL separately.' WHERE service_id = '657';""")
    op.execute("""UPDATE service SET service_desc = 'Back office duty for specifically assigned SBC staff only - Employment Standards Branch   ' WHERE service_id = '726';""")
    op.execute("""UPDATE service SET service_desc = 'Preparing Ballot Bundles and mailing to Elections BC (Back office duty).  VERY IMPORTANT: Adjust the transaction  s "Quantity" number to match the number of   Bundles   being mailed.' WHERE service_id = '763';""")
    op.execute("""UPDATE service SET service_desc = 'Room booking, setup, and management of room bookings for Ministries etc. ' WHERE service_id = '798';""")
    op.execute("""UPDATE service SET service_desc = 'All Contact Tracing Calls - TRACK EACH CALL SEPARATELY' WHERE service_id = '836';""")
    op.execute("""UPDATE service SET service_desc = 'Transportation of Hazardous Waste exam invigilation - Includes All Pre-Preparation, During, and Post duties performed for Onsite One-Off Exam Invigilation.  i.e.  from scheduling in The Q to submitting completed exam.' WHERE service_id = '869';""")
    op.execute("""UPDATE service SET service_desc = 'Transportation of Hazardous Waste group exam invigilation - Includes receiving and checking exam materials, pre-preparation of materials for Invigilator (or SBC Staff), post preparation of completed exams and submission.' WHERE service_id = '870';""")
    op.execute("""UPDATE service SET service_desc = 'Transportation of Hazardous Waste group exam invigilation - Includes receiving and checking exam materials, pre-preparation of materials for Invigilator (or SBC Staff), post preparation of completed exams and submission.' WHERE service_id = '871';""")
    op.execute("""UPDATE service SET service_desc = 'Transportation of Hazardous Waste group exam invigilation - Includes receiving and checking exam materials, pre-preparation of materials for Invigilator (or SBC Staff), post preparation of completed exams and submission.' WHERE service_id = '872';""")
    op.execute("""UPDATE service SET service_desc = 'Pesticide Licence - New application - Providing information, reviewing application for completeness, accepting payment (SC 0431), submitting application on the citizens   behalf, returning original etc.          ' WHERE service_id = '874';""")
    op.execute("""UPDATE service SET service_desc = 'Pesticide Licence - Renewal application - Providing information, reviewing application for completeness, accepting payment (SC 0432), submitting application on the citizens   behalf, returning original etc' WHERE service_id = '875';""")
    op.execute("""UPDATE service SET service_desc = 'Transportation of Hazardous Waste licence - New application:  Providing information, reviewing application for completeness, accepting payment (SC 1539), submitting application on citizens   behalf, returning original etc.' WHERE service_id = '876';""")
    op.execute("""UPDATE service SET service_desc = 'Transportation of Hazardous Waste licence - Renewal application:  Providing information, reviewing application for completeness, accepting payment (SC 1540) submitting application on the citizens   behalf, returning original etc.' WHERE service_id = '877';""")
    op.execute("""UPDATE service SET service_desc = 'All Tier 2 - Online ID Verifications completed, field support provided, and additional work assigned as a Specialist.' WHERE service_id = '878';""")
    op.execute("""UPDATE service SET service_desc = 'Speculation Tax, SVT - Providing General Information' WHERE service_id = '911';""")
    op.execute("""UPDATE service SET service_desc = 'FSSS office taking a phone Payment for GVA - Receive citizen contact information from GVA, phone citizen from PCI compliant phone, process payment for New (SC1539) or Renewal (SC 1540) licence in eGarms, scan/email copy of receipt to GVA.        ' WHERE service_id = '912';""")
    op.execute("""UPDATE service SET service_desc = 'FSSS office taking a phone Payment for GVA -   Receive citizen contact information from GVA, phone citizen from PCI compliant phone, process payment for New (SC 0431) or Renewal (SC 0432) licence in eGarms, scan/email copy of receipt to GVA.' WHERE service_id = '913';""")
    op.execute("""UPDATE service SET service_desc = 'Employment Standards Branch (ESB) Tier 2 -  Providing team support/answering questions, developing training/reference materials, provide training, Quality Assurance etc.' WHERE service_id = '915';""")
    op.execute("""UPDATE service SET service_desc = 'Centralized Municipal Home Owner Grant - Process HOG in Gentax on behalf of home owner' WHERE service_id = '916';""")
    op.execute("""UPDATE service SET service_desc = 'IMMS - Responding to an Ad Hoc/Misc. enquiry in the vaccination booking Call Back queue' WHERE service_id = '1050';""")
    op.execute("""UPDATE service SET service_desc = 'CPG - Community Gaming Grant Program 2021 - Provide general application or contact information, scan and email documentation to citizen in support of their application, direct citizen to CATs if applying in the office.' WHERE service_id = '1052';""")
    op.execute("""UPDATE service SET service_desc = 'Transportation of Hazardous Waste licence - New AND Renewal application received by email:  Reviewing application for completeness and submitting on citizens   behalf.  IMPORTANT:  Track phone payment using   THW/PEST - email app. Payment   service type.' WHERE service_id = '1053';""")
    op.execute("""UPDATE service SET service_desc = 'Pesticide Licence - New AND Renewal application received by email - Reviewing application for completeness and submitting on the citizens   behalf. IMPORTANT: Track phone payment using   THW/PEST - email app. Payment   service type.' WHERE service_id = '1054';""")
    op.execute("""UPDATE service SET service_desc = 'For offices that have a CSR(s), triage the line up to determine reason for visit, to advise of wait times, redirect etc.  PPE required.' WHERE service_id = '1055';""")
    op.execute("""UPDATE service SET service_desc = 'When CSR is getting Personal or Office related PC/Network technical assistance from 250-387-7000; either by phone or when submitting an online request.  ' WHERE service_id = '1056';""")
    op.execute("""UPDATE service SET service_desc = 'prepping and confirming refund amounts, calculations, review' WHERE service_id = '1058';""")
    op.execute("""UPDATE service SET service_desc = 'Partial Refunds due to air quality' WHERE service_id = '1161';""")
    op.execute("""UPDATE service SET service_desc = 'Assiting with booking COVID19 tests for Vancouver Island Health Authority' WHERE service_id = '1233';""")
    op.execute("""UPDATE service SET service_desc = 'CATe Pharmacy contact', prefix = 'A' WHERE service_id = '1278';""")
    op.execute("""UPDATE service SET service_desc = 'Pathfinding and providing assistance to citizens using online tools', prefix = 'A' WHERE service_id = '1286';""")
    op.execute("""UPDATE service SET service_desc = 'Ministry of Transportation and Infrastructure' WHERE service_id = '1359';""")
    op.execute("""UPDATE service SET service_desc = 'Used by MSC SCSR  s to review Federal and Provincial benefit programs through the online benefit finder tool' WHERE service_id = '1466';""")


def downgrade():

    # Generated SQL commands for downgrade (rollback)
    op.execute("""UPDATE service SET service_desc = 'Used by MSC SCSR  s to review Federal and Provincial benefit programs through the online benefit finder tool' WHERE service_id = '1466';""")
    op.execute("""UPDATE service SET service_desc = 'Ministry of Transportation and Infrastructure ' WHERE service_id = '1359';""")
    op.execute("""UPDATE service SET service_desc = 'Pathfinding and providing assistance to citizens using online tools ', prefix = 'a' WHERE service_id = '1286';""")
    op.execute("""UPDATE service SET service_desc = 'CATe Pharmacy contact ', prefix = 'a' WHERE service_id = '1278';""")
    op.execute("""UPDATE service SET service_desc = 'Assiting with booking COVID19 tests for Vancouver Island Health Authority ' WHERE service_id = '1233';""")
    op.execute("""UPDATE service SET service_desc = 'Partial Refunds due to air quality ' WHERE service_id = '1161';""")
    op.execute("""UPDATE service SET service_desc = 'prepping and confirming refund amounts, calculations, review ' WHERE service_id = '1058';""")
    op.execute("""UPDATE service SET service_desc = 'When CSR is getting Personal or Office related PC/Network technical assistance from 250-387-7000; either by phone or when submitting an online request.   ' WHERE service_id = '1056';""")
    op.execute("""UPDATE service SET service_desc = 'For offices that have a CSR(s), triage the line up to determine reason for visit, to advise of wait times, redirect etc.   PPE required. ' WHERE service_id = '1055';""")
    op.execute("""UPDATE service SET service_desc = 'Pesticide Licence    New AND Renewal application received by email - Reviewing application for completeness and submitting on the citizens   behalf. IMPORTANT: Track phone payment using   THW/PEST    email app. Payment   service type.' WHERE service_id = '1054';""")
    op.execute("""UPDATE service SET service_desc = 'Transportation of Hazardous Waste licence    New AND Renewal application received by email:   Reviewing application for completeness and submitting on citizens   behalf.   IMPORTANT:   Track phone payment using   THW/PEST    email app. Payment   service type.' WHERE service_id = '1053';""")
    op.execute("""UPDATE service SET service_desc = 'CPG - Community Gaming Grant Program 2021    Provide general application or contact information, scan and email documentation to citizen in support of their application, direct citizen to CATs if applying in the office. ' WHERE service_id = '1052';""")
    op.execute("""UPDATE service SET service_desc = 'IMMS    Responding to an Ad Hoc/Misc. enquiry in the vaccination booking Call Back queue' WHERE service_id = '1050';""")
    op.execute("""UPDATE service SET service_desc = 'Centralized Municipal Home Owner Grant    Process HOG in Gentax on behalf of home owner' WHERE service_id = '916';""")
    op.execute("""UPDATE service SET service_desc = 'Employment Standards Branch (ESB) Tier 2 -   Providing team support/answering questions, developing training/reference materials, provide training, Quality Assurance etc.' WHERE service_id = '915';""")
    op.execute("""UPDATE service SET service_desc = 'FSSS office taking a phone Payment for GVA -     Receive citizen contact information from GVA, phone citizen from PCI compliant phone, process payment for New (SC 0431) or Renewal (SC 0432) licence in eGarms, scan/email copy of receipt to GVA.' WHERE service_id = '913';""")
    op.execute("""UPDATE service SET service_desc = 'FSSS office taking a phone Payment for GVA - Receive citizen contact information from GVA, phone citizen from PCI compliant phone, process payment for New (SC1539) or Renewal (SC 1540) licence in eGarms, scan/email copy of receipt to GVA.  ' WHERE service_id = '912';""")
    op.execute("""UPDATE service SET service_desc = 'Speculation Tax, SVT    Providing General Information ' WHERE service_id = '911';""")
    op.execute("""UPDATE service SET service_desc = 'All Tier 2 - Online ID Verifications completed, field support provided, and additional work assigned as a Specialist.  ' WHERE service_id = '878';""")
    op.execute("""UPDATE service SET service_desc = 'Transportation of Hazardous Waste licence - Renewal application:   Providing information, reviewing application for completeness, accepting payment (SC 1540) submitting application on the citizens   behalf, returning original etc.' WHERE service_id = '877';""")
    op.execute("""UPDATE service SET service_desc = 'Transportation of Hazardous Waste licence - New application:   Providing information, reviewing application for completeness, accepting payment (SC 1539), submitting application on citizens   behalf, returning original etc. ' WHERE service_id = '876';""")
    op.execute("""UPDATE service SET service_desc = 'Pesticide Licence - Renewal application - Providing information, reviewing application for completeness, accepting payment (SC 0432), submitting application on the citizens   behalf, returning original etc' WHERE service_id = '875';""")
    op.execute("""UPDATE service SET service_desc = 'Pesticide Licence - New application - Providing information, reviewing application for completeness, accepting payment (SC 0431), submitting application on the citizens   behalf, returning original etc.      ' WHERE service_id = '874';""")
    op.execute("""UPDATE service SET service_desc = 'Transportation of Hazardous Waste group exam invigilation    Includes receiving and checking exam materials, pre-preparation of materials for Invigilator (or SBC Staff), post preparation of completed exams and submission.' WHERE service_id = '872';""")
    op.execute("""UPDATE service SET service_desc = 'Transportation of Hazardous Waste group exam invigilation    Includes receiving and checking exam materials, pre-preparation of materials for Invigilator (or SBC Staff), post preparation of completed exams and submission.' WHERE service_id = '871';""")
    op.execute("""UPDATE service SET service_desc = 'Transportation of Hazardous Waste group exam invigilation    Includes receiving and checking exam materials, pre-preparation of materials for Invigilator (or SBC Staff), post preparation of completed exams and submission.' WHERE service_id = '870';""")
    op.execute("""UPDATE service SET service_desc = 'Transportation of Hazardous Waste exam invigilation    Includes All Pre-Preparation, During, and Post duties performed for Onsite One-Off Exam Invigilation.   i.e.   from scheduling in The Q to submitting completed exam.' WHERE service_id = '869';""")
    op.execute("""UPDATE service SET service_desc = 'All Contact Tracing Calls    TRACK EACH CALL SEPARATELY' WHERE service_id = '836';""")
    op.execute("""UPDATE service SET service_desc = 'Room booking, setup, and management of room bookings for Ministries etc.   ' WHERE service_id = '798';""")
    op.execute("""UPDATE service SET service_desc = 'Preparing Ballot Bundles and mailing to Elections BC (Back office duty).  VERY IMPORTANT: Adjust the transaction  s "Quantity" number to match the number of   Bundles   being mailed.   ' WHERE service_id = '763';""")
    op.execute("""UPDATE service SET service_desc = 'Back office duty for specifically assigned SBC staff only - Employment Standards Branch     ' WHERE service_id = '726';""")
    op.execute("""UPDATE service SET service_desc = 'Traveler Project - Calls to Temporary Foreign Workers ONLY.  TRACK EACH CALL separately.  ' WHERE service_id = '657';""")
    op.execute("""UPDATE service SET service_desc = 'Online ID Verification process (includes verifying, rejecting, and contacting/forwarding to Tier 2 for assistance or completion).  TRACK EACH VERIFICATION separately. ' WHERE service_id = '656';""")
    op.execute("""UPDATE service SET service_desc = 'All Tier 2 support calls and reporting correlated to the COVID Traveler project.  TRACK EACH CALL separately. ' WHERE service_id = '655';""")
    op.execute("""UPDATE service SET service_desc = 'All calls and reporting correlated to the COVID Traveler project.  TRACK EACH CALL separately.  ' WHERE service_id = '654';""")
    op.execute("""UPDATE service SET service_desc = 'All office cleaning and sanitizing correlated to staff and citizen safety during the COVID pandemic. ' WHERE service_id = '653';""")
    op.execute("""UPDATE service SET service_desc = 'All office cleaning and sanitizing correlated to staff and citizen safety during the COVID pandemic. ' WHERE service_id = '652';""")
    op.execute("""UPDATE service SET service_desc = 'F&W - Royalty Payments, Any BACK OFFICE work issuing licences/creating FWIDs for Guides  (i.e.  bulk drop off  licence requests).  Track FRONT COUNTER  services as Hunting    Non-Resident' WHERE service_id = '619';""")
    op.execute("""UPDATE service SET service_desc = 'MSP- Providing/reviewing applications, forwarding to HIBC. ' WHERE service_id = '618';""")
    op.execute("""UPDATE service SET service_desc = 'RTB    Providing Information for general program and application processes, RTB contact info, printing and providing forms' WHERE service_id = '617';""")
    op.execute("""UPDATE service SET service_desc = 'RTB - Application for Review, Correction/Clarification ' WHERE service_id = '609';""")
    op.execute("""UPDATE service SET service_desc = 'RTB - Preparing hearing packages for pick up, submitting applications for amendment ' WHERE service_id = '606';""")
    op.execute("""UPDATE service SET service_desc = 'Professional Excellence Team Members only; attend Training Team meetings, communication, developing training material, TIMS data entry, training budgets, etc. ' WHERE service_id = '601';""")
    op.execute("""UPDATE service SET service_desc = 'SC800, Speculation Tax, SVT, taking a vacancy SVT   payment.' WHERE service_id = '575';""")
    op.execute("""UPDATE service SET service_desc = 'Client Liaison/Program Specialist for SkilledTradesBC; Includes Job Aid work, CSR related meetings, document creation, field assistance, etc.', email_paragraph = '' WHERE service_id = '533';""")
    op.execute("""UPDATE service SET service_desc = 'SC 1664    Completing a Worker Attestation, Taking $100 payment, Witnessing signature, coping ID, scanning to LCRB etc.' WHERE service_id = '510';""")
    op.execute("""UPDATE service SET service_desc = 'Assisting citizen with SBC App. guidance/access issues. ' WHERE service_id = '490';""")
    op.execute("""UPDATE service SET service_desc = 'SDPR 3rd Party - Emptying stub drop box, scanning stubs, preparing mail.  ' WHERE service_id = '463';""")
    op.execute("""UPDATE service SET service_desc = 'SDPR POC - weekly reports to SDPR, mail sorting if applicable (not cheques), monthly batching mail out to SDPR etc. ' WHERE service_id = '418';""")
    op.execute("""UPDATE service SET service_desc = 'SDPR 3rd Party - Assisting individual clients with imprest cheque pick up, cancelling and mailing per SDPR direction. This includes client tracking and signatures (if applicable). ' WHERE service_id = '412';""")
    op.execute("""UPDATE service SET service_desc = 'MCFD - Contract agreements, Coding blocks, Purchase documents, Petty Cash (holder of) and reconciliation,  Respite/Relief forms, ' WHERE service_id = '385';""")
    op.execute("""UPDATE service SET service_desc = 'ICBC Auto - Cancel Policy ' WHERE service_id = '352';""")
    op.execute("""UPDATE service SET service_desc = 'ICBC Auto - Commission Tracking ' WHERE service_id = '340';""")
    op.execute("""UPDATE service SET service_desc = 'ICBC - Road Test Set up/Result: RT -  Either put it on hold or end it after the test set up. When client returns, you either resume or create a new one. ' WHERE service_id = '316';""")
    op.execute("""UPDATE service SET service_desc = 'ICBC - Knowledge Test Set up/Result: KT - Either put it on hold or end it after the test set up. When client returns, you either resume or create a new one. ' WHERE service_id = '310';""")
    op.execute("""UPDATE service SET service_desc = 'Batching ' WHERE service_id = '247';""")
    op.execute("""UPDATE service SET service_desc = 'Redirect - Directing citizen to the Office Phone to self serve ' WHERE service_id = '232';""")
    op.execute("""UPDATE service SET service_desc = 'Providing Information for misc. programs, applications such as gaming, photocopies, faxes, misc. forms, Front Counter BC, Human Rights Tribunal, Public Trustee, Legal Aid, bereavement checklist, foreign pension, Safer, HAFI, BC Housing, Seafood Licencing etc.     Payments such as ministry collections and student loans (e.g., Service Code 1278/Revenue Services of BC (RSBC), MCFD SC1459, , Mineral Tax., Mineral Inspection, , Bridge Toll etc.' WHERE service_id = '220';""")
    op.execute("""UPDATE service SET service_desc = 'Notary - All Notary duties. ' WHERE service_id = '217';""")
    op.execute("""UPDATE service SET service_desc = 'PEST-Can include PRE, DURING and/or POST for offsite invigilation.  ' WHERE service_id = '178';""")
    op.execute("""UPDATE service SET service_desc = 'PEST Invigilation - one-off;  Pre/During/Post - All work involved from scheduling the candidate, to uploading the completed materials.   ' WHERE service_id = '175';""")
    op.execute("""UPDATE service SET service_desc = 'Exams-Providing Information about all exams, invigilation of other exams such as angling/guide outfitter exam, veterinary exam, bulk tank milk grader exam, ITA card replacement etc. ' WHERE service_id = '172';""")
    op.execute("""UPDATE service SET service_desc = 'SkilledTradesBC - Checking for expired exams, contacting SkilledTradesBC program, mailing back SkilledTradesBC etc.' WHERE service_id = '169';""")
    op.execute("""UPDATE service SET service_desc = 'SkilledTradesBC - Can include PRE, DURING and/or POST for offsite invigilation.  ', email_paragraph = '' WHERE service_id = '166';""")
    op.execute("""UPDATE service SET service_desc = 'SkilledTradesBC - Checking exam materials, copying or scanning exam, mailing etc.' WHERE service_id = '163';""")
    op.execute("""UPDATE service SET service_desc = 'SkilledTradesBC   Invigilation - one-off;  Pre/During/Post - All work involved from receiving the exam, to mailing the completed exam and materials to SkilledTradesBC and BC Mail. ' WHERE service_id = '160';""")
    op.execute("""UPDATE service SET service_desc = 'BC Online - All searches using BC Online i.e. BC Assessment/Man Homes/Company & Society searches/PPR Lien search etc. ' WHERE service_id = '151';""")
    op.execute("""UPDATE service SET service_desc = 'RTB    Assisting citizens with online applications at CATs.  Back office duties such as management of Abandoned files.  Other misc. services' WHERE service_id = '142';""")
    op.execute("""UPDATE service SET service_desc = 'MSP- SC686, SC1089, SC1278  - Outstanding MSP payments, International Student Health Fee. ' WHERE service_id = '109';""")
    op.execute("""UPDATE service SET service_desc = 'F&W - hunter needing FWID only or update to account (do not use this code if looking up is part of hunting license or LEH issuance) ' WHERE service_id = '61';""")