"""empty message

Revision ID: 44c03a3c8a83
Revises: ca3161acb1d3
Create Date: 2019-11-11 15:41:43.558756

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '44c03a3c8a83'
down_revision = 'ca3161acb1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('upload_received_ind', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'upload_received_ind')
    # ### end Alembic commands ###
