"""sbcq155

Revision ID: 4bf4b127aaa4
Revises: ba295f379d0d
Create Date: 2024-07-26 09:41:48.557375

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bf4b127aaa4'
down_revision = 'ba295f379d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('office', sa.Column('optout_status', sa.Integer(), nullable=False, server_default='0'))
   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('office', 'optout_status')
    
    # ### end Alembic commands ###
