"""empty message

Revision ID: 4f3e25700ad5
Revises: 0e0a38cb41aa
Create Date: 2019-03-19 12:56:47.992012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3e25700ad5'
down_revision = '0e0a38cb41aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office', sa.Column('appointments_enabled_ind', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('office', 'appointments_enabled_ind')
    # ### end Alembic commands ###
