"""SBCQ-302

Revision ID: 50f3691868ed
Revises: 8b6c67545310
Create Date: 2024-12-18 17:18:48.088463

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '50f3691868ed'
down_revision = '8b6c67545310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('partner', sa.String(), nullable=True))
    op.add_column('service', sa.Column('program', sa.String(), nullable=True))
    op.add_column('service', sa.Column('recoverable', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'recoverable')
    op.drop_column('service', 'program')
    op.drop_column('service', 'partner')
    # ### end Alembic commands ###
