"""sbcq242_external_service_name

Revision ID: 516321784cb2
Revises: 42ee86bb6d2e
Create Date: 2024-10-09 17:12:09.576247

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '516321784cb2'
down_revision = '42ee86bb6d2e'
branch_labels = None
depends_on = None


def upgrade():

    # Generated SQL commands for upgrade
    op.execute("""UPDATE service SET external_service_name = 'ICBC' WHERE service_id = '19';""")
    op.execute("""UPDATE service SET external_service_name = 'MCFD' WHERE service_id = '25';""")
    op.execute("""UPDATE service SET external_service_name = 'Property Tax' WHERE service_id = '34';""")
    op.execute("""UPDATE service SET external_service_name = 'Income & Disability Assistance' WHERE service_id = '46';""")
    op.execute("""UPDATE service SET external_service_name = 'ID Verification' WHERE service_id = '52';""")
    op.execute("""UPDATE service SET external_service_name = 'Water, Land and Resource Stewardship: Fishing Licence (Freshwater Angling)' WHERE service_id = '55';""")
    op.execute("""UPDATE service SET external_service_name = 'Water, Land and Resource Stewardship: Fish & Wildlife ID (Hunter Number)' WHERE service_id = '58';""")
    op.execute("""UPDATE service SET external_service_name = 'Water, Land and Resource Stewardship: Fish and Wildlife Identification and Account Update Only' WHERE service_id = '61';""")
    op.execute("""UPDATE service SET external_service_name = 'Water, Land and Resource Stewardship: Resident Hunting Licence, Tags, and Limited Entry Hunting (LEH)' WHERE service_id = '64';""")
    op.execute("""UPDATE service SET external_service_name = 'Water, Land and Resource Stewardship: Fish and Wildlife Vendor Management' WHERE service_id = '73';""")
    op.execute("""UPDATE service SET external_service_name = 'Health: Birth Certificate' WHERE service_id = '79';""")
    op.execute("""UPDATE service SET external_service_name = 'Health: Marriage Licence' WHERE service_id = '82';""")
    op.execute("""UPDATE service SET external_service_name = 'Health: Legal Change of Name' WHERE service_id = '85';""")
    op.execute("""UPDATE service SET external_service_name = 'Health: Death Certificate, Wills Notice, Wills Search' WHERE service_id = '88';""")
    op.execute("""UPDATE service SET external_service_name = 'Health: General Vital Stats Information  and Services' WHERE service_id = '91';""")
    op.execute("""UPDATE service SET external_service_name = 'Finance: Rural Property Tax - Payment and/or Claim Homeowner Grant' WHERE service_id = '94';""")
    op.execute("""UPDATE service SET external_service_name = 'Finance: Property Tax - Deferment Payment' WHERE service_id = '97';""")
    op.execute("""UPDATE service SET external_service_name = 'Finance: Property Tax - Deferment Application' WHERE service_id = '103';""")
    op.execute("""UPDATE service SET external_service_name = 'Finance: General Property Tax Information' WHERE service_id = '106';""")
    op.execute("""UPDATE service SET external_service_name = 'Health: Medical Services Plan Payment' WHERE service_id = '109';""")
    op.execute("""UPDATE service SET external_service_name = 'Health: BC Services Card with Photo' WHERE service_id = '112';""")
    op.execute("""UPDATE service SET external_service_name = 'Health: BC Services Card - Non-Photo Card - To order call 1-800-663-7100' WHERE service_id = '115';""")
    op.execute("""UPDATE service SET external_service_name = 'Health: Medical Services Plan Account Update' WHERE service_id = '118';""")
    op.execute("""UPDATE service SET external_service_name = 'Health: Medical Services Plan Application for BC Medical' WHERE service_id = '121';""")
    op.execute("""UPDATE service SET external_service_name = 'Health: Medical Services Plan - General Services' WHERE service_id = '127';""")
    op.execute("""UPDATE service SET external_service_name = 'BC Hydro: Payment' WHERE service_id = '130';""")
    op.execute("""UPDATE service SET external_service_name = 'Finance: Provincial Sales Tax (PST) Payments' WHERE service_id = '133';""")
    op.execute("""UPDATE service SET external_service_name = 'Housing: Residential Tenancy - Dispute Application' WHERE service_id = '139';""")
    op.execute("""UPDATE service SET external_service_name = 'Housing: Residential Tenancy - Miscellaneous Tasks' WHERE service_id = '142';""")
    op.execute("""UPDATE service SET external_service_name = 'Citizens'' Services: Manufactured, Mobile or Trailer Homes' WHERE service_id = '145';""")
    op.execute("""UPDATE service SET external_service_name = ' Citizens''  Services: Personal Property (Motor Vehicle) Liens' WHERE service_id = '148';""")
    op.execute("""UPDATE service SET external_service_name = ' Citizens''  Services: Business Registration, Name Request and Management' WHERE service_id = '154';""")
    op.execute("""UPDATE service SET external_service_name = ' Citizens''  Services: Skilled Trades BC Exam Management' WHERE service_id = '169';""")
    op.execute("""UPDATE service SET external_service_name = 'Environment and Climate Change Strategy: Providing Exam Support and Services' WHERE service_id = '172';""")
    op.execute("""UPDATE service SET external_service_name = 'Finance: Ambulance Service Fee Payment' WHERE service_id = '181';""")
    op.execute("""UPDATE service SET external_service_name = ' Citizens''  Services: BCeID ID Verification (Personal or Business)' WHERE service_id = '184';""")
    op.execute("""UPDATE service SET external_service_name = 'Attorney General: Commissioner for Taking Affidavits (Limited Authority)' WHERE service_id = '190';""")
    op.execute("""UPDATE service SET external_service_name = 'Attorney General: Court Fine Payment' WHERE service_id = '202';""")
    op.execute("""UPDATE service SET external_service_name = 'Water, Land and Resource Stewardship: Crown Land Lease/Water Payment' WHERE service_id = '208';""")
    op.execute("""UPDATE service SET external_service_name = 'Public Service Agency: Administering the Oath of Employment - One on One' WHERE service_id = '211';""")
    op.execute("""UPDATE service SET external_service_name = 'Public Service Agency: Administering the Oath of Employment - Group' WHERE service_id = '214';""")
    op.execute("""UPDATE service SET external_service_name = 'Attorney General: Notary (Limited Authority)' WHERE service_id = '217';""")
    op.execute("""UPDATE service SET external_service_name = 'Service Canada: Redirecting to Employment Insurance Services' WHERE service_id = '223';""")
    op.execute("""UPDATE service SET external_service_name = 'Service Canada: Redirecting to a non Service BC Governmental Program' WHERE service_id = '226';""")
    op.execute("""UPDATE service SET external_service_name = 'Service Canada: Redirecting to Municipal Program Services' WHERE service_id = '229';""")
    op.execute("""UPDATE service SET external_service_name = 'Service Canada: Redirecting to another Governmental Service' WHERE service_id = '238';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): Ticket Payment or Dispute' WHERE service_id = '292';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): Address Change' WHERE service_id = '295';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): Additional Information and Services' WHERE service_id = '298';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): BC Services Card Issuance - New Card and Renewal Services Only' WHERE service_id = '301';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): BC Driver Licence, BC Services Card and/or BCID' WHERE service_id = '304';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): BC Drivers Licence Switch Over Drivers Licence after Moving to BC' WHERE service_id = '307';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): Reinstatement of BC Drivers License and/or IRP Fees' WHERE service_id = '310';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): BC Driver Knowledge Test (All Classes)' WHERE service_id = '313';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): Book a Road/Driving Test' WHERE service_id = '316';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): Vehicle Impound Release and Driving Prohibition Review' WHERE service_id = '319';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): Driving Record/Abstract' WHERE service_id = '322';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): ID Hold Release' WHERE service_id = '325';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): Batching and Filing Services for ICBC' WHERE service_id = '334';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): Inventory Audit for ICBC Auto Sevices' WHERE service_id = '337';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): Commision Tracking for ICBC Auto Services' WHERE service_id = '340';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): Autoplan - Change/Renew Policy' WHERE service_id = '343';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): ICBC Auto Renewal Policies' WHERE service_id = '346';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): Autoplan Temporary Operating Permit' WHERE service_id = '349';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): Autoplan - Cancel Policy' WHERE service_id = '352';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): Autoplan Transfer Insurance/Same Owner' WHERE service_id = '355';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): Autoplan Fleet Renewals' WHERE service_id = '358';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): Additional ICBC Auto Services' WHERE service_id = '361';""")
    op.execute("""UPDATE service SET external_service_name = 'Children and Family Development: Administrative Services' WHERE service_id = '364';""")
    op.execute("""UPDATE service SET external_service_name = 'Children and Family Development: Record Management Services' WHERE service_id = '367';""")
    op.execute("""UPDATE service SET external_service_name = 'Children and Family Development: Affordable Child Care Benefit' WHERE service_id = '370';""")
    op.execute("""UPDATE service SET external_service_name = 'Children and Family Development: General Services' WHERE service_id = '373';""")
    op.execute("""UPDATE service SET external_service_name = 'Children and Family Development: File Management Services' WHERE service_id = '376';""")
    op.execute("""UPDATE service SET external_service_name = 'Children and Family Development: Reception Services' WHERE service_id = '379';""")
    op.execute("""UPDATE service SET external_service_name = 'Children and Family Development: Integrated Case Management Services' WHERE service_id = '382';""")
    op.execute("""UPDATE service SET external_service_name = 'Children and Family Development: Financial Services' WHERE service_id = '385';""")
    op.execute("""UPDATE service SET external_service_name = 'Children and Family Development: Joint Occupational Health and Safety Services' WHERE service_id = '388';""")
    op.execute("""UPDATE service SET external_service_name = 'Children and Family Development: Child Youth Mental Health' WHERE service_id = '391';""")
    op.execute("""UPDATE service SET external_service_name = 'Children and Family Development: Fleet Maintenance Services' WHERE service_id = '394';""")
    op.execute("""UPDATE service SET external_service_name = 'Children and Family Development: Off Site Integrated Case Management Record Keeping Services' WHERE service_id = '397';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: 3rd Party - Income and Disability Assistance' WHERE service_id = '400';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: 3rd Party New Applicant Services' WHERE service_id = '403';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: 3rd Party Food Voucher Services' WHERE service_id = '406';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: 3rd Party Monthly Cheque Distribution' WHERE service_id = '409';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: 3rd Party Cheque Imprest Services' WHERE service_id = '412';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: SDPR - General Information - New or Existing Clients' WHERE service_id = '415';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: SDPR Admin - Processing Services' WHERE service_id = '418';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: SDPR Admin - Stub Services SD81' WHERE service_id = '421';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: SDPR Admin - Cheque Services' WHERE service_id = '424';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: Income and Disability Assistance - Cheque Pick-up' WHERE service_id = '427';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: MySelfServe Assistance - Existing Clients' WHERE service_id = '430';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: Income and Disability Assistance - Submit Service Request' WHERE service_id = '433';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: Income and Disability Assistance - Update Service Request' WHERE service_id = '436';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: Income and Disability Assistance - Apply for Income Assistance' WHERE service_id = '439';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: 3rd Party Information Services Only' WHERE service_id = '442';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: SDPR - Repayment Services' WHERE service_id = '445';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: 3rd Party Repayment Services' WHERE service_id = '448';""")
    op.execute("""UPDATE service SET external_service_name = 'Insurance Corporation of Bristish Columbia (ICBC): Estate, and Ownership Transfer, and New Registration for ICBC Auto' WHERE service_id = '451';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: 3rd Party Admin - Cheque Services' WHERE service_id = '454';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: 3rd Party Admin - Miscellaneous' WHERE service_id = '457';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: 3rd Party Admin - Stock Inventory Services' WHERE service_id = '460';""")
    op.execute("""UPDATE service SET external_service_name = 'Social Development and Poverty Reduction: 3rd Party Admin - Stub Services SD81' WHERE service_id = '463';""")
    op.execute("""UPDATE service SET external_service_name = 'Housing: Residential Tenancy - Submit Additional Evidence' WHERE service_id = '466';""")
    op.execute("""UPDATE service SET external_service_name = ' Citizens''  Services: Service BC Application Information' WHERE service_id = '487';""")
    op.execute("""UPDATE service SET external_service_name = ' Citizens''  Services: Service BC Application Assistance' WHERE service_id = '490';""")
    op.execute("""UPDATE service SET external_service_name = ' Citizens''  Services: BC Services Card - Verify Mobile Card' WHERE service_id = '493';""")
    op.execute("""UPDATE service SET external_service_name = 'LCRB' WHERE service_id = '504';""")
    op.execute("""UPDATE service SET external_service_name = 'Attorney General: Cannabis and Liquor Information and Licensing' WHERE service_id = '519';""")
    op.execute("""UPDATE service SET external_service_name = 'Children and Family Development: Autism Funding' WHERE service_id = '522';""")
    op.execute("""UPDATE service SET external_service_name = 'Finance: Speculation and Vacancy Tax - Payment' WHERE service_id = '575';""")
    op.execute("""UPDATE service SET external_service_name = 'Housing: Residential Tenancy - Pick-up Hearing Package' WHERE service_id = '606';""")
    op.execute("""UPDATE service SET external_service_name = 'Housing: Residential Tenancy - General Information and Processing' WHERE service_id = '617';""")
    op.execute("""UPDATE service SET external_service_name = ' Citizens''  Services: Online Verification Services' WHERE service_id = '656';""")
    op.execute("""UPDATE service SET external_service_name = 'Environment and Climate Change Strategy: Pesticide Exams' WHERE service_id = '797';""")
    op.execute("""UPDATE service SET external_service_name = 'Environment and Climate Change Strategy: Transportation of Hazardous Waste Exams' WHERE service_id = '873';""")
    op.execute("""UPDATE service SET external_service_name = ' Citizens''  Services: Tier 2 Online Verification Services' WHERE service_id = '878';""")
    op.execute("""UPDATE service SET external_service_name = 'Finance: General Speculation Tax Information' WHERE service_id = '911';""")
    op.execute("""UPDATE service SET external_service_name = 'Finance: Centralized Municipal Home Owner Grant Process - On Behalf of the Home Owner' WHERE service_id = '916';""")
    op.execute("""UPDATE service SET external_service_name = 'Finance: General Centralized Municipal Home Owner Grant Information' WHERE service_id = '917';""")
    op.execute("""UPDATE service SET external_service_name = 'Health: Vaccine Booking; visit online or call 1-833-838-2323' WHERE service_id = '950';""")
    op.execute("""UPDATE service SET external_service_name = 'Health: General Vaccine Information Only' WHERE service_id = '951';""")
    op.execute("""UPDATE service SET external_service_name = 'Health: Vaccine Registration; visit online or call 1-833-838-2323', online_link = 'https:\\www2.gov.bc.ca/getvaccinated.html' WHERE service_id = '984';""")
    op.execute("""UPDATE service SET external_service_name = 'Health: Ad Hoc Vaccine Call Backs and Requests' WHERE service_id = '1050';""")
    op.execute("""UPDATE service SET external_service_name = 'ICBC services not available here; find your closest driver licensing office in Online Options', online_link = 'https://www.icbc.com/locators/Pages/default.aspx' WHERE service_id = '1051';""")
    op.execute("""UPDATE service SET external_service_name = 'Health: Proof of vaccination and the BC Vaccine Card' WHERE service_id = '1059';""")
    op.execute("""UPDATE service SET external_service_name = ' Citizens''  Services: BC Registry Name Request' WHERE service_id = '1195';""")
    op.execute("""UPDATE service SET external_service_name = ' Citizens''  Services: BC Token Password Reset Only' WHERE service_id = '1280';""")
    op.execute("""UPDATE service SET external_service_name = ' Citizens''  Services: New and Replacement BC Token Services' WHERE service_id = '1282';""")
    op.execute("""UPDATE service SET external_service_name = ' Citizens''  Services: Searches conducted for all business entities' WHERE service_id = '1287';""")
    op.execute("""UPDATE service SET external_service_name = 'Public Safety and Solicitor General' WHERE service_id = '1532';""")
    op.execute("""UPDATE service SET external_service_name = 'Public Safety and Solicitor General: Public Safety and Solicitor General: Poster services for missing and murdered indigenous people' WHERE service_id = '1533';""")
    op.execute("""UPDATE service SET external_service_name = 'Public Safety and Solicitor General: Poster services for missing and murdered indigenous people' WHERE service_id = '1534';""")
    op.execute("""UPDATE service SET external_service_name = 'Emergency Response' WHERE service_id = '1535';""")
    op.execute("""UPDATE service SET external_service_name = ' Citizens''  Services: Profile Creation Support for Evacuee Registration and Assistance Application' WHERE service_id = '1536';""")


def downgrade():

    # Generated SQL commands for downgrade (rollback)
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '1536';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '1535';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '1534';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '1533';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '1532';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '1287';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '1282';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '1280';""")
    op.execute("""UPDATE service SET external_service_name = 'BC Registry name request' WHERE service_id = '1195';""")
    op.execute("""UPDATE service SET external_service_name = 'Proof of vaccination and the BC Vaccine Card' WHERE service_id = '1059';""")
    op.execute("""UPDATE service SET external_service_name = 'ICBC services not available here; find your closest driver licensing office in Online Options  ', online_link = 'https://www.icbc.com/locators/Pages/default.aspx  ' WHERE service_id = '1051';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '1050';""")
    op.execute("""UPDATE service SET external_service_name = 'Vaccine Registration; visit online or call 1-833-838-2323', online_link = 'https:\www2.gov.bc.ca/getvaccinated.html' WHERE service_id = '984';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '951';""")
    op.execute("""UPDATE service SET external_service_name = 'Vaccine Booking; visit online or call 1-833-838-2323' WHERE service_id = '950';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '917';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '916';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '911';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '878';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '873';""")
    op.execute("""UPDATE service SET external_service_name = 'Pesticide Exams - Please Call the Office to Book Your Written Exam Appointment ' WHERE service_id = '797';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '656';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '617';""")
    op.execute("""UPDATE service SET external_service_name = 'Residential Tenancy - Pick-up Hearing Package' WHERE service_id = '606';""")
    op.execute("""UPDATE service SET external_service_name = 'Autism Funding' WHERE service_id = '522';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '519';""")
    op.execute("""UPDATE service SET external_service_name = 'Liquor Licensing' WHERE service_id = '504';""")
    op.execute("""UPDATE service SET external_service_name = 'BC Services Card - Verify Mobile Card' WHERE service_id = '493';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '490';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '487';""")
    op.execute("""UPDATE service SET external_service_name = 'Residential Tenancy - Submit Additional Evidence' WHERE service_id = '466';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '463';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '460';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '457';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '454';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '451';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '448';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '445';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '442';""")
    op.execute("""UPDATE service SET external_service_name = 'Income and Disability Assistance - Apply for Income Assistance' WHERE service_id = '439';""")
    op.execute("""UPDATE service SET external_service_name = 'Income and Disability Assistance - Update Service Request' WHERE service_id = '436';""")
    op.execute("""UPDATE service SET external_service_name = 'Income and Disability Assistance - Submit Service Request' WHERE service_id = '433';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '430';""")
    op.execute("""UPDATE service SET external_service_name = 'Income and Disability Assistance - Cheque Pick-up' WHERE service_id = '427';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '424';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '421';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '418';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '415';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '412';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '409';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '406';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '403';""")
    op.execute("""UPDATE service SET external_service_name = 'Income and Disability Assistance' WHERE service_id = '400';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '397';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '394';""")
    op.execute("""UPDATE service SET external_service_name = 'Child Youth Mental Health (CYMH)' WHERE service_id = '391';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '388';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '385';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '382';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '379';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '376';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '373';""")
    op.execute("""UPDATE service SET external_service_name = 'Affordable Child Care Benefit' WHERE service_id = '370';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '367';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '364';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '361';""")
    op.execute("""UPDATE service SET external_service_name = 'ICBC Autoplan - Fleet Renewals' WHERE service_id = '358';""")
    op.execute("""UPDATE service SET external_service_name = 'ICBC Autoplan - Transfer Insurance/Same Owner' WHERE service_id = '355';""")
    op.execute("""UPDATE service SET external_service_name = 'ICBC Autoplan - Cancel Policy' WHERE service_id = '352';""")
    op.execute("""UPDATE service SET external_service_name = 'ICBC Autoplan - Temporary Operating Permit' WHERE service_id = '349';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '346';""")
    op.execute("""UPDATE service SET external_service_name = 'ICBC Autoplan - Change/Renew Policy' WHERE service_id = '343';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '340';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '337';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '334';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '325';""")
    op.execute("""UPDATE service SET external_service_name = 'Driving Record/Abstract' WHERE service_id = '322';""")
    op.execute("""UPDATE service SET external_service_name = 'Vehicle Impound Release and Driving Prohibition Review' WHERE service_id = '319';""")
    op.execute("""UPDATE service SET external_service_name = 'Book a road/driving test at ICBC.com/roadtest ' WHERE service_id = '316';""")
    op.execute("""UPDATE service SET external_service_name = 'BC Driver Knowledge Test (All Classes)' WHERE service_id = '313';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '310';""")
    op.execute("""UPDATE service SET external_service_name = 'BC Drivers Licence Switch Over Drivers Licence after Moving to BC' WHERE service_id = '307';""")
    op.execute("""UPDATE service SET external_service_name = 'BC Driver Licence, BC Services Card and/or BCID' WHERE service_id = '304';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '301';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '298';""")
    op.execute("""UPDATE service SET external_service_name = 'Address Change' WHERE service_id = '295';""")
    op.execute("""UPDATE service SET external_service_name = 'Ticket Payment or Dispute' WHERE service_id = '292';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '238';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '229';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '226';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '223';""")
    op.execute("""UPDATE service SET external_service_name = 'Notary (Limited Authority)' WHERE service_id = '217';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '214';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '211';""")
    op.execute("""UPDATE service SET external_service_name = 'Crown Land Lease/Water Payment' WHERE service_id = '208';""")
    op.execute("""UPDATE service SET external_service_name = 'Court Fine Payment' WHERE service_id = '202';""")
    op.execute("""UPDATE service SET external_service_name = 'Commissioner for Taking Affidavits (Limited Authority)' WHERE service_id = '190';""")
    op.execute("""UPDATE service SET external_service_name = 'BCeID ID Verification (Personal or Business)' WHERE service_id = '184';""")
    op.execute("""UPDATE service SET external_service_name = 'Ambulance Service Fee Payment' WHERE service_id = '181';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '172';""")
    op.execute("""UPDATE service SET external_service_name = NULL, email_paragraph = '' WHERE service_id = '169';""")
    op.execute("""UPDATE service SET external_service_name = 'Business Registration, Name Request and Management' WHERE service_id = '154';""")
    op.execute("""UPDATE service SET external_service_name = 'Personal Property (Motor Vehicle) Liens' WHERE service_id = '148';""")
    op.execute("""UPDATE service SET external_service_name = 'Manufactured, Mobile or Trailer Homes' WHERE service_id = '145';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '142';""")
    op.execute("""UPDATE service SET external_service_name = 'Residential Tenancy - Dispute Application' WHERE service_id = '139';""")
    op.execute("""UPDATE service SET external_service_name = 'Provincial Sales Tax (PST) Payments' WHERE service_id = '133';""")
    op.execute("""UPDATE service SET external_service_name = 'BC Hydro Payment-Online Only' WHERE service_id = '130';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '127';""")
    op.execute("""UPDATE service SET external_service_name = 'Medical Services Plan Application for BC Medical' WHERE service_id = '121';""")
    op.execute("""UPDATE service SET external_service_name = 'Medical Services Plan Account Update' WHERE service_id = '118';""")
    op.execute("""UPDATE service SET external_service_name = 'BC Services Card - Non-photo Card-to order call 1-800-663-7100' WHERE service_id = '115';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '112';""")
    op.execute("""UPDATE service SET external_service_name = 'Medical Services Plan Payment' WHERE service_id = '109';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '106';""")
    op.execute("""UPDATE service SET external_service_name = 'Rural Property Tax - Deferment Application' WHERE service_id = '103';""")
    op.execute("""UPDATE service SET external_service_name = 'Rural Property Tax - Deferment Payment' WHERE service_id = '97';""")
    op.execute("""UPDATE service SET external_service_name = 'Rural Property Tax - Payment and/or Claim Homeowner Grant' WHERE service_id = '94';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '91';""")
    op.execute("""UPDATE service SET external_service_name = 'Death Certificate, Wills Notice, Wills Search' WHERE service_id = '88';""")
    op.execute("""UPDATE service SET external_service_name = 'Legal Change of Name' WHERE service_id = '85';""")
    op.execute("""UPDATE service SET external_service_name = 'Marriage Licence' WHERE service_id = '82';""")
    op.execute("""UPDATE service SET external_service_name = 'Birth Certificate ' WHERE service_id = '79';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '73';""")
    op.execute("""UPDATE service SET external_service_name = 'Resident Hunting Licence, Tags, and Limited Entry Hunting (LEH)' WHERE service_id = '64';""")
    op.execute("""UPDATE service SET external_service_name = NULL WHERE service_id = '61';""")
    op.execute("""UPDATE service SET external_service_name = 'Fish & Wildlife ID (Hunter Number)' WHERE service_id = '58';""")
    op.execute("""UPDATE service SET external_service_name = 'Fishing Licence (Freshwater Angling)' WHERE service_id = '55';""")
    op.execute("""UPDATE service SET external_service_name = 'BC Services Card Verification' WHERE service_id = '52';""")
    op.execute("""UPDATE service SET external_service_name = 'Income & Disability Assistance ' WHERE service_id = '46';""")
    op.execute("""UPDATE service SET external_service_name = 'Rural Property Tax' WHERE service_id = '34';""")
    op.execute("""UPDATE service SET external_service_name = 'Child Care (Ministry of Children and Families)' WHERE service_id = '25';""")
    op.execute("""UPDATE service SET external_service_name = 'Driver Licensing & ID' WHERE service_id = '19';""")