"""empty message

Revision ID: 52a334670eb7
Revises: ca0e1b21ff7c
Create Date: 2018-10-30 16:13:44.280232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a334670eb7'
down_revision = 'ca0e1b21ff7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen', sa.Column('service_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizen', 'service_count')
    # ### end Alembic commands ###
