"""empty message

Revision ID: 57ecc6d6c916
Revises: f54ebb773f4c
Create Date: 2019-03-24 21:21:29.410534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ecc6d6c916'
down_revision = 'f54ebb773f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counter',
    sa.Column('counter_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('counter_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['office.office_id'], ),
    sa.PrimaryKeyConstraint('counter_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counter')
    # ### end Alembic commands ###
