"""empty message

Revision ID: 633a3bd11056
Revises: 89294ac623e8
Create Date: 2020-07-08 14:13:40.093832

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '633a3bd11056'
down_revision = '89294ac623e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csr', sa.Column('ita2_designate', sa.Integer(), server_default="0", nullable=False))
    op.add_column('csr', sa.Column('office_manager', sa.Integer(), server_default="0", nullable=False))
    op.create_index(op.f('ix_publicuser_username'), 'publicuser', ['username'], unique=True)
    # ### end Alembic commands ###

    #   Copy data from old fields to new fields
    op.execute("update csr set ita2_designate=liaison_designate")
    op.execute("update csr set office_manager=ita_designate")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publicuser_username'), table_name='publicuser')
    op.drop_column('csr', 'office_manager')
    op.drop_column('csr', 'ita2_designate')
    # ### end Alembic commands ###
