"""appointment_version

Revision ID: 638fb4b2f2d5
Revises: 13f777964cf9
Create Date: 2021-03-29 14:51:16.826384

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc

# revision identifiers, used by Alembic.
revision = '638fb4b2f2d5'
down_revision = '13f777964cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_version',
                    sa.Column('appointment_id', sa.Integer(), autoincrement=False, nullable=False),
                    sa.Column('office_id', sa.Integer(), autoincrement=False, nullable=True),
                    sa.Column('service_id', sa.Integer(), autoincrement=False, nullable=True),
                    sa.Column('citizen_id', sa.Integer(), autoincrement=False, nullable=True),
                    sa.Column('start_time', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), autoincrement=False,
                              nullable=True),
                    sa.Column('end_time', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), autoincrement=False,
                              nullable=True),
                    sa.Column('checked_in_time', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
                              autoincrement=False, nullable=True),
                    sa.Column('comments', sa.String(length=255), autoincrement=False, nullable=True),
                    sa.Column('citizen_name', sa.String(length=255), autoincrement=False, nullable=True),
                    sa.Column('contact_information', sa.String(length=255), autoincrement=False, nullable=True),
                    sa.Column('blackout_flag', sa.String(length=1), autoincrement=False, nullable=True),
                    sa.Column('recurring_uuid', sa.String(length=255), autoincrement=False, nullable=True),
                    sa.Column('online_flag', sa.Boolean(), autoincrement=False, nullable=True),
                    sa.Column('is_draft', sa.Boolean(), autoincrement=False, nullable=True),
                    sa.Column('created_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), autoincrement=False,
                              nullable=True),
                    sa.Column('stat_flag', sa.Boolean(), autoincrement=False, nullable=True),
                    sa.Column('updated_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), autoincrement=False,
                              nullable=True),
                    sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True),
                    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
                    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
                    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
                    sa.PrimaryKeyConstraint('appointment_id', 'transaction_id')
                    )
    op.create_index(op.f('ix_appointment_version_end_transaction_id'), 'appointment_version', ['end_transaction_id'],
                    unique=False)
    op.create_index(op.f('ix_appointment_version_operation_type'), 'appointment_version', ['operation_type'],
                    unique=False)
    op.create_index(op.f('ix_appointment_version_transaction_id'), 'appointment_version', ['transaction_id'],
                    unique=False)
    op.create_table('transaction',
                    sa.Column('issued_at', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('remote_addr', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('appointment',
                  sa.Column('updated_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True))
    op.add_column('appointment', sa.Column('updated_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'updated_by')
    op.drop_column('appointment', 'updated_at')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_appointment_version_transaction_id'), table_name='appointment_version')
    op.drop_index(op.f('ix_appointment_version_operation_type'), table_name='appointment_version')
    op.drop_index(op.f('ix_appointment_version_end_transaction_id'), table_name='appointment_version')
    op.drop_table('appointment_version')
    # ### end Alembic commands ###
