"""empty message

Revision ID: 651bd7a2cae6
Revises: b4ac5c82cb5b
Create Date: 2021-03-04 15:55:02.387921

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '651bd7a2cae6'
down_revision = 'b4ac5c82cb5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen', sa.Column('notification_email', sa.String(length=100), nullable=True))
    op.add_column('citizen', sa.Column('notification_phone', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizen', 'notification_phone')
    op.drop_column('citizen', 'notification_email')
    # ### end Alembic commands ###
