"""empty message

Revision ID: 65c4064116f4
Revises: f78833b67a10
Create Date: 2020-10-21 08:45:51.779155

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '65c4064116f4'
down_revision = 'f78833b67a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('is_draft', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'is_draft')
    # ### end Alembic commands ###
