"""empty message

Revision ID: 6bc6bb570986
Revises: d15137046e4e
Create Date: 2021-03-09 12:13:12.284098

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '6bc6bb570986'
down_revision = 'd15137046e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen', sa.Column('walkin_unique_id', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizen', 'walkin_unique_id')
    # ### end Alembic commands ###
