"""empty message

Revision ID: 6c1511e233c6
Revises: 755d0f8eded1
Create Date: 2018-09-04 17:47:57.799939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1511e233c6'
down_revision = '755d0f8eded1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen', sa.Column('accurate_time_ind', sa.Integer(), nullable=False))
    op.drop_column('period', 'accurate_time_ind')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('accurate_time_ind', sa.INTEGER(), nullable=False))
    op.drop_column('citizen', 'accurate_time_ind')
    # ### end Alembic commands ###
