"""empty message

Revision ID: 71486b5dce97
Revises: ca2023cc8b00
Create Date: 2020-12-07 13:27:50.709682

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '71486b5dce97'
down_revision = 'ca2023cc8b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office', sa.Column('external_map_link', sa.String(length=500), nullable=True))
    op.drop_column('service', 'external_map_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('external_map_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('office', 'external_map_link')
    # ### end Alembic commands ###
