"""empty message

Revision ID: 88de5dfe8dec
Revises: b0f5b7b6acf7
Create Date: 2019-01-10 11:06:30.399651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88de5dfe8dec'
down_revision = 'b0f5b7b6acf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizen', 'service_count')
    op.add_column('servicereq', sa.Column('sr_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicereq', 'sr_number')
    op.add_column('citizen', sa.Column('service_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
