"""empty message

Revision ID: 8a64b7726c2c
Revises: 91572a9309f0
Create Date: 2021-03-05 13:52:45.696007

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '8a64b7726c2c'
down_revision = '91572a9309f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen', sa.Column('reminder_flag', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizen', 'reminder_flag')
    # ### end Alembic commands ###
