"""empty message

Revision ID: 8a939073b36f
Revises: 641db6e01015
Create Date: 2020-11-23 11:23:52.231462

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '8a939073b36f'
down_revision = '641db6e01015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('email_paragraph', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'email_paragraph')
    # ### end Alembic commands ###
