"""sbcq156

Revision ID: 8b6c67545310
Revises: 4bf4b127aaa4
Create Date: 2024-07-26 10:13:02.148021

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b6c67545310'
down_revision = '4bf4b127aaa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.alter_column('office', 'optout_status',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('office', 'optout_status',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    
    # ### end Alembic commands ###
