"""empty message

Revision ID: 91572a9309f0
Revises: dd9947c84076
Create Date: 2021-03-05 13:52:16.321087

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '91572a9309f0'
down_revision = 'dd9947c84076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizen', 'reminder_flag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen', sa.Column('reminder_flag', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
