"""empty message

Revision ID: 92cd814a5c05
Revises: 129ea023f600
Create Date: 2019-10-22 16:31:58.046195

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92cd814a5c05'
down_revision = '129ea023f600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('citizen_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointment', 'citizen', ['citizen_id'], ['citizen_id'])
    # ### end Alembic commands ###

    #  Insert a record into the citizen state table.



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'citizen_id')
    # ### end Alembic commands ###
