"""empty message

Revision ID: 92cd814a5c05
Revises: 129ea023f600
Create Date: 2019-10-22 16:31:58.046195

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92cd814a5c05'
down_revision = '129ea023f600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citizen_archive')
    op.drop_table('archive')
    op.drop_table('period_archive')
    op.drop_table('servicereq_archive')
    op.add_column('appointment', sa.Column('citizen_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointment', 'citizen', ['citizen_id'], ['citizen_id'])
    # ### end Alembic commands ###

    #  Insert a record into the citizen state table.



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'citizen_id')
    op.create_table('servicereq_archive',
    sa.Column('sr_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('citizen_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sr_state_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sr_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('sr_id', name='servicereq_archive_pkey')
    )
    op.create_table('period_archive',
    sa.Column('period_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sr_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('csr_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reception_csr_ind', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ps_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('time_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('period_id', name='period_archive_pkey')
    )
    op.create_table('archive',
    sa.Column('archive_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('archive_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id_min', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_max', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('archive_id', name='archive_pkey')
    )
    op.create_table('citizen_archive',
    sa.Column('citizen_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('office_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('counter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ticket_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('citizen_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('citizen_comments', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('qt_xn_citizen_ind', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cs_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('accurate_time_ind', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('citizen_id', name='citizen_archive_pkey')
    )
    # ### end Alembic commands ###
