"""empty message

Revision ID: a05659940088
Revises: 5b3921d80d78
Create Date: 2020-01-12 16:23:24.976867

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = 'a05659940088'
down_revision = '5b3921d80d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('invigilator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exam', 'invigilator', ['invigilator_id'], ['invigilator_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.drop_column('exam', 'invigilator_id')
    # ### end Alembic commands ###
