"""online_appointment_changes

Revision ID: ad4ef26eff9c
Revises: 1171a9129db4
Create Date: 2020-04-17 17:30:50.836327

"""
import sqlalchemy as sa
import sqlalchemy_utc
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad4ef26eff9c'
down_revision = '1171a9129db4'
branch_labels = None
depends_on = None

availability = postgresql.ENUM('SHOW', 'HIDE', 'DISABLE', name='availability')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    availability.create(op.get_bind())

    op.create_table('holiday',
                    sa.Column('holiday_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('year', sa.Integer(), nullable=True),
                    sa.Column('holiday', sa.Date(), nullable=True),
                    sa.PrimaryKeyConstraint('holiday_id')
                    )
    op.create_table('publicuser',
                    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('username', sa.String(length=100), nullable=True),
                    sa.Column('display_name', sa.String(length=200), nullable=True),
                    sa.Column('email', sa.String(length=200), nullable=True),
                    sa.Column('telephone', sa.String(length=20), nullable=True),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    op.create_table('timeslot',
                    sa.Column('time_slot_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('start_time', sa.Time(), nullable=False),
                    sa.Column('end_time', sa.Time(), nullable=False),
                    sa.Column('day_of_week', sa.Integer(), nullable=True),
                    sa.Column('no_of_slots', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('time_slot_id')
                    )
    op.create_table('office_timeslot',
                    sa.Column('office_id', sa.Integer(), nullable=False),
                    sa.Column('time_slot_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['office_id'], ['office.office_id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['time_slot_id'], ['timeslot.time_slot_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('office_id', 'time_slot_id')
                    )
    op.create_table('officeclosure',
                    sa.Column('closure_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('office_id', sa.Integer(), nullable=False),
                    sa.Column('start_date', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
                    sa.Column('end_date', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
                    sa.Column('users_notified', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['office_id'], ['office.office_id'], ),
                    sa.PrimaryKeyConstraint('closure_id')
                    )
    op.add_column('citizen', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('citizen_publicuser_fkey', 'citizen', 'publicuser', ['user_id'], ['user_id'])
    op.add_column('office', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('office', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('office', sa.Column('office_appointment_message', sa.String(length=1000), nullable=True))
    op.add_column('service', sa.Column('external_service_name', sa.String(length=500), nullable=True))
    op.add_column('service', sa.Column('online_availability', sa.Enum('SHOW', 'HIDE', 'DISABLE', name='availability'),
                                       nullable=True))
    op.add_column('service', sa.Column('online_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'online_link')
    op.drop_column('service', 'online_availability')
    op.drop_column('service', 'external_service_name')
    op.drop_column('office', 'office_appointment_message')
    op.drop_column('office', 'longitude')
    op.drop_column('office', 'latitude')
    op.drop_constraint('citizen_publicuser_fkey', 'citizen', type_='foreignkey')
    op.drop_column('citizen', 'user_id')
    op.drop_table('officeclosure')
    op.drop_table('office_timeslot')
    op.drop_table('timeslot')
    op.drop_table('publicuser')
    op.drop_table('holiday')

    availability.drop(op.get_bind())

    # ### end Alembic commands ###
