"""empty message

Revision ID: ad82a83aa9ed
Revises: e479ceee0190
Create Date: 2019-02-18 17:24:22.337731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad82a83aa9ed'
down_revision = 'e479ceee0190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('sbc_staff_invigilated', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'sbc_staff_invigilated')
    # ### end Alembic commands ###
