"""empty message

Revision ID: b0f5b7b6acf7
Revises: 2fc4029b8645
Create Date: 2018-12-19 13:48:02.118918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f5b7b6acf7'
down_revision = '2fc4029b8645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('exam_returned_ind', sa.Integer(), nullable=False))
    op.add_column('exam', sa.Column('exam_returned_tracking_number', sa.String(length=50), nullable=True))
    op.add_column('examtype', sa.Column('group_exam_ind', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('examtype', 'group_exam_ind')
    op.drop_column('exam', 'exam_returned_tracking_number')
    op.drop_column('exam', 'exam_returned_ind')
    # ### end Alembic commands ###
