"""empty message

Revision ID: b490a42c008d
Revises: 5a4c3719dac5
Create Date: 2018-11-09 19:56:03.630429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b490a42c008d'
down_revision = '5a4c3719dac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csr', sa.Column('priority', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csr', 'priority')
    # ### end Alembic commands ###
