"""empty message

Revision ID: b4ac5c82cb5b
Revises: 62686ac6eefc
Create Date: 2021-03-04 16:30:40.418579

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = 'b4ac5c82cb5b'
down_revision = '62686ac6eefc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office', sa.Column('automatic_reminder_at', sa.Integer(), nullable=True))
    op.add_column('office', sa.Column('check_in_notification', sa.Integer(), nullable=True))
    op.add_column('office', sa.Column('check_in_reminder_msg', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('office', 'check_in_reminder_msg')
    op.drop_column('office', 'check_in_notification')
    op.drop_column('office', 'automatic_reminder_at')
    # ### end Alembic commands ###
