"""citizen start position column add

Revision ID: ba295f379d0d
Revises: d84abcbcf722
Create Date: 2022-05-24 21:33:54.034171

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = 'ba295f379d0d'
down_revision = 'd84abcbcf722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen', sa.Column('start_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizen', 'start_position')
    # ### end Alembic commands ###
