"""empty message

Revision ID: c25c4ee67df6
Revises: 8a939073b36f
Create Date: 2020-11-23 12:38:56.311121

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = 'c25c4ee67df6'
down_revision = '8a939073b36f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office', sa.Column('office_email_paragraph', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('office', 'office_email_paragraph')
    # ### end Alembic commands ###
