"""empty message

Revision ID: c388edd5dc5a
Revises: 8b6c67545310
Create Date: 2026-03-27 08:50:06.260961

"""

import sqlalchemy as sa
import sqlalchemy_utc
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c388edd5dc5a"
down_revision = "8b6c67545310"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exam", schema=None) as batch_op:
        batch_op.alter_column(
            "expiry_date",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            type_=sa.DateTime(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "exam_received_date",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            type_=sa.DateTime(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "exam_returned_date",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            type_=sa.DateTime(),
            existing_nullable=True,
        )

    with op.batch_alter_table("publicuser", schema=None) as batch_op:
        batch_op.alter_column(
            "last_name",
            existing_type=sa.VARCHAR(length=200),
            type_=sa.String(length=100),
            existing_nullable=True,
        )

    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.alter_column(
            "external_service_name",
            existing_type=sa.VARCHAR(length=500),
            type_=sa.String(length=100),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "online_link",
            existing_type=sa.VARCHAR(length=500),
            type_=sa.String(length=200),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.alter_column(
            "online_link",
            existing_type=sa.String(length=200),
            type_=sa.VARCHAR(length=500),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "external_service_name",
            existing_type=sa.String(length=100),
            type_=sa.VARCHAR(length=500),
            existing_nullable=True,
        )

    with op.batch_alter_table("publicuser", schema=None) as batch_op:
        batch_op.alter_column(
            "last_name",
            existing_type=sa.String(length=100),
            type_=sa.VARCHAR(length=200),
            existing_nullable=True,
        )

    with op.batch_alter_table("exam", schema=None) as batch_op:
        batch_op.alter_column(
            "exam_returned_date",
            existing_type=sa.DateTime(),
            type_=postgresql.TIMESTAMP(timezone=True),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "exam_received_date",
            existing_type=sa.DateTime(),
            type_=postgresql.TIMESTAMP(timezone=True),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "expiry_date",
            existing_type=sa.DateTime(),
            type_=postgresql.TIMESTAMP(timezone=True),
            existing_nullable=True,
        )

    op.create_table(
        "appointment_version",
        sa.Column("appointment_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("office_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("service_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("citizen_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "start_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "end_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "checked_in_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "comments", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "citizen_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "contact_information",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "blackout_flag", sa.VARCHAR(length=1), autoincrement=False, nullable=True
        ),
        sa.Column(
            "recurring_uuid", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("online_flag", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_draft", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("stat_flag", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("updated_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("transaction_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "end_transaction_id", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("operation_type", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint(
            "appointment_id", "transaction_id", name=op.f("appointment_version_pkey")
        ),
    )
    with op.batch_alter_table("appointment_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_appointment_version_transaction_id"),
            ["transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_appointment_version_operation_type"),
            ["operation_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_appointment_version_end_transaction_id"),
            ["end_transaction_id"],
            unique=False,
        )

    op.create_table(
        "transaction",
        sa.Column(
            "issued_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "remote_addr", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("transaction_pkey")),
    )
    # ### end Alembic commands ###
