"""empty message

Revision ID: c47b250bf785
Revises: da480f231142
Create Date: 2019-03-21 10:28:59.517183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47b250bf785'
down_revision = 'da480f231142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office', sa.Column('timezone_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'office', 'timezone', ['timezone_id'], ['timezone_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'office', type_='foreignkey')
    op.drop_column('office', 'timezone_id')
    # ### end Alembic commands ###
