"""empty message

Revision ID: c6e752f35c56
Revises: 06f4ae2201d8
Create Date: 2019-03-28 11:25:36.982406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e752f35c56'
down_revision = '06f4ae2201d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('citizen_name', sa.String(length=255), nullable=False))
    op.add_column('appointment', sa.Column('contact_information', sa.String(length=255), nullable=True))
    op.add_column('appointment', sa.Column('service_id', sa.Integer(), nullable=False))
    op.drop_column('appointment', 'category')
    op.create_foreign_key(None, 'appointment', 'service', ['service_id'], ['service_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'service_id')
    op.drop_column('appointment', 'contact_information')
    op.drop_column('appointment', 'citizen_name')
    op.add_column('appointment', sa.Column('category', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###
