"""empty message

Revision ID: ca2023cc8b00
Revises: 198b2c9110b9
Create Date: 2020-12-07 13:22:16.353600

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = 'ca2023cc8b00'
down_revision = '198b2c9110b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('external_map_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'external_map_link')
    # ### end Alembic commands ###
