"""empty message

Revision ID: ca3161acb1d3
Revises: 7564bc97ed99
Create Date: 2019-11-11 15:35:01.305946

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = 'ca3161acb1d3'
down_revision = '7564bc97ed99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('exam_destroyed_date', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'exam_destroyed_date')
    # ### end Alembic commands ###
