"""empty message

Revision ID: cf50e7b9a32c
Revises: eee726e68b4a
Create Date: 2019-01-03 15:06:32.505650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf50e7b9a32c'
down_revision = 'eee726e68b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('invigilator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'booking', 'invigilator', ['invigilator_id'], ['invigilator_id'])
    op.drop_constraint('exam_ibfk_3', 'exam', type_='foreignkey')
    op.drop_column('exam', 'invigilator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('invigilator_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('exam_ibfk_3', 'exam', 'invigilator', ['invigilator_id'], ['invigilator_id'])
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_column('booking', 'invigilator_id')
    # ### end Alembic commands ###
