"""empty message

Revision ID: d15137046e4e
Revises: eb3330757f6e
Create Date: 2021-03-05 15:44:17.225635

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = 'd15137046e4e'
down_revision = 'eb3330757f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen', sa.Column('notification_sent_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizen', 'notification_sent_time')
    # ### end Alembic commands ###
