"""online_appointments_2

Revision ID: d195a426f111
Revises: ad4ef26eff9c
Create Date: 2020-04-22 23:30:39.437435

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = 'd195a426f111'
down_revision = 'ad4ef26eff9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office', sa.Column('appointments_days_limit', sa.Integer(), nullable=True))
    op.add_column('office', sa.Column('appointment_duration', sa.Integer(), nullable=True))
    op.add_column('office', sa.Column('max_person_appointment_per_day', sa.Integer(), nullable=True))

    op.execute('update office set appointments_days_limit=30')
    op.execute('update office set appointment_duration=30')
    op.execute('update office set max_person_appointment_per_day=1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('office', 'appointments_days_limit')
    op.drop_column('office', 'max_person_appointment_per_day')
    op.drop_column('office', 'appointment_duration')

    # ### end Alembic commands ###
