"""online_appointments_2

Revision ID: d195a426f111
Revises: ad4ef26eff9c
Create Date: 2020-04-22 23:30:39.437435

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = 'd195a426f111'
down_revision = 'ad4ef26eff9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office', sa.Column('appointments_days_limit', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_publicuser_username'), 'publicuser', ['username'], unique=True)
    op.execute('update office set appointments_days_limit=30')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publicuser_username'), table_name='publicuser')
    op.drop_column('office', 'appointments_days_limit')
    # ### end Alembic commands ###
