"""empty message

Revision ID: d19d82e2bd34
Revises: c6e752f35c56
Create Date: 2019-04-17 11:58:25.737327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19d82e2bd34'
down_revision = 'c6e752f35c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examtype', sa.Column('number_of_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('examtype', 'number_of_minutes')
    # ### end Alembic commands ###
