"""add_exam_type

Revision ID: d84abcbcf722
Revises: 4b4bac23d407
Create Date: 2021-05-11 12:02:17.628186

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = 'd84abcbcf722'
down_revision = '4b4bac23d407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examtype', sa.Column('deleted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('examtype', 'deleted')
    # ### end Alembic commands ###
