"""empty message

Revision ID: d9db7e1f2f4f
Revises: 651bd7a2cae6
Create Date: 2021-03-04 20:13:57.242389

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = 'd9db7e1f2f4f'
down_revision = '651bd7a2cae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen', sa.Column('notification_sent_time', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizen', 'notification_sent_time')
    # ### end Alembic commands ###
