"""empty message

Revision ID: da480f231142
Revises: 0e0a38cb41aa
Create Date: 2019-03-21 10:24:09.610576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da480f231142'
down_revision = '4f3e25700ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timezone',
    sa.Column('timezone_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timezone_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('timezone_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timezone')
    # ### end Alembic commands ###
