"""empty message

Revision ID: dab7f099460e
Revises: c1b93103c752
Create Date: 2019-08-20 12:16:17.115416

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = 'dab7f099460e'
down_revision = 'c1b93103c752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('blackout_flag', sa.String(length=1), server_default='N', nullable=False))
    op.alter_column('appointment', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('booking', sa.Column('blackout_flag', sa.String(length=1), server_default='N', nullable=False))
    op.add_column('booking', sa.Column('blackout_notes', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'blackout_notes')
    op.drop_column('booking', 'blackout_flag')
    op.alter_column('appointment', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('appointment', 'blackout_flag')
    # ### end Alembic commands ###
