"""empty message

Revision ID: e4cc072c7df0
Revises: 6bc6bb570986
Create Date: 2021-03-21 19:03:22.784071

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = 'e4cc072c7df0'
down_revision = '6bc6bb570986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen', sa.Column('automatic_reminder_flag', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizen', 'automatic_reminder_flag')
    # ### end Alembic commands ###
