"""empty message

Revision ID: eb3330757f6e
Revises: 8a64b7726c2c
Create Date: 2021-03-05 15:43:44.657383

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb3330757f6e'
down_revision = '8a64b7726c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizen', 'notification_sent_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen', sa.Column('notification_sent_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
