"""empty message

Revision ID: eee726e68b4a
Revises: 2fc4029b8645
Create Date: 2018-12-19 10:36:17.211244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee726e68b4a'
down_revision = '2fc4029b8645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office', sa.Column('exams_enabled_ind', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('office', 'exams_enabled_ind')
    # ### end Alembic commands ###
