"""empty message

Revision ID: f6234fc92d1c
Revises: 3f8e6c8468f1
Create Date: 2019-02-05 12:08:35.553294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6234fc92d1c'
down_revision = '3f8e6c8468f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam', 'expiry_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam', 'expiry_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
