"""Add dlkt to service and office

Revision ID: f78833b67a10
Revises: 2118a4e8e321
Create Date: 2020-09-30 12:24:07.750703

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f78833b67a10'
down_revision = '2118a4e8e321'
branch_labels = None
depends_on = None

yesno = postgresql.ENUM('YES', 'NO', name='yesno')

def upgrade():
    yesno.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office', sa.Column('number_of_dlkt', sa.Integer(), nullable=True))
    op.add_column('service', sa.Column('is_dlkt', sa.Enum('YES', 'NO', name='yesno'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'is_dlkt')
    op.drop_column('office', 'number_of_dlkt')
    # ### end Alembic commands ###
    yesno.drop(op.get_bind())
