"""adding_office_address

Revision ID: fc3fd3bab5bc
Revises: d195a426f111
Create Date: 2020-04-25 22:09:36.415006

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = 'fc3fd3bab5bc'
down_revision = 'd195a426f111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office', sa.Column('civic_address', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('office', 'civic_address')
    # ### end Alembic commands ###
