name: Build Pull Request
on:
  workflow_dispatch:
    inputs:
      pr-number:
        description: Pull Request Number
        required: true
      namespace:
        type: choice
        description: Namespace
        options: 
        - QMS
        - TheQ

jobs:

  ##### SETUP ######################################################################################

  note:
    name: Building refs/pull/${{ github.event.inputs.pr-number }}/head to ${{ github.event.inputs.namespace }}
    runs-on: ubuntu-latest

    steps:
    - name: Output
      run: echo Building refs/pull/${{ github.event.inputs.pr-number }}/head to ${{ github.event.inputs.namespace }}

  create-image-tags:
    name: Create Image Tags
    needs: note
    runs-on: ubuntu-latest
    outputs:
      image-tags: ${{ steps.get-image-tags.outputs.image-tags }}

    steps:
    - name: Get Image Tags
      id: get-image-tags
      run: |
        IMAGE_TAGS=pr${{ steps.get-image-tags.outputs.image-tags }}
        echo Using tags: \"$IMAGE_TAGS\"
        echo "::set-output name=image-tags::$IMAGE_TAGS"

  ##### BUILD ######################################################################################

  appointment-frontend:
    name: appointment-frontend
    needs: create-image-tags
    uses: walter-moar/queue-management/.github/workflows/reusable-build-dockerfile.yaml@master
    secrets:
      artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      artifactory-registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
      artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      namespace-theq: ${{ secrets.NAMESPACE_THEQ }}
      namespace-theq-password: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}
      namespace-theq-username: ${{ secrets.NAMESPACE_THEQ_USERNAME }}
      namespace-qms: ${{ secrets.NAMESPACE_QMS }}
      namespace-qms-password: ${{ secrets.NAMESPACE_QMS_PASSWORD }}
      namespace-qms-username: ${{ secrets.NAMESPACE_QMS_USERNAME }}
      openshift-registry: ${{ secrets.OPENSHIFT_REGISTRY }}
    with:
      directory: appointment-frontend
      image-name: appointment-frontend
      image-tags: ${{ needs.create-image-tags.outputs.image-tags }}
      namespaces: ${{ github.event.inputs.namespace }}

#   build:
#     name: Dockerfile Build
#     needs: create-image-tags
#     runs-on: ubuntu-latest
# #     outputs:
# #       image-tags: ${{ steps.build-image.outputs.tags }}

#     steps:
#     - name: echo
#       run: |
#         echo ${{ github.event.inputs.pr-number }}
#         echo refs/pull/${{ github.event.inputs.pr-number }}/head

#     - name: Check out
#       uses: actions/checkout@v2
#       with:
#           ref: refs/pull/${{ github.event.inputs.pr-number }}/head
          
#     - name: meow
#       run: |
#         # ls -laR
#         cat .github/workflows/README.md

#     - name: Login to Artifactory to Pull Images in Buildah Build
#       uses: redhat-actions/podman-login@v1
#       with:
#         registry: ${{ secrets.artifactory-registry }}
#         username: ${{ secrets.artifactory-username }}
#         password: ${{ secrets.artifactory-password }}

#     - name: Buildah Build
#       id: build-image
#       uses: redhat-actions/buildah-build@v2
#       with:
#         containerfiles: ${{ inputs.directory }}/Dockerfile
#         context: ${{ inputs.directory }}
#         image: ${{ inputs.image-name }}
#         tags: ${{ inputs.image-tags }}
