name: Build Pull Request
on:
  workflow_dispatch:
    inputs:
      pr-number:
        description: "Pull Request Number:"
        required: true
      namespace:
        type: choice
        description: "Deploy To:"
        options:
        - TheQ Dev
        - QMS Dev
        - TheQ Test

jobs:

  ##### SETUP ######################################################################################

  parse-namespace:
    name: refs/pull/${{ github.event.inputs.pr-number }}/head to ${{ github.event.inputs.namespace }}
    runs-on: ubuntu-latest
    outputs:
      push-qms: ${{ steps.parse.outputs.push-qms }}
      push-theq: ${{ steps.parse.outputs.push-theq }}
      deploy-dev: ${{ steps.parse.outputs.deploy-dev }}
      deploy-test: ${{ steps.parse.outputs.deploy-test }}

    steps:
    - name: Parse Namespace
      id: parse
      run: |
        PUSH_QMS=$(if [[ "${{ github.event.inputs.namespace }}" == QMS* ]]; then echo true; else echo false; fi)
        PUSH_THEQ=$(if [[ "${{ github.event.inputs.namespace }}" == TheQ* ]]; then echo true; else echo false; fi)
        DEPLOY_DEV=$(if [[ "${{ github.event.inputs.namespace }}" == *Dev ]]; then echo true; else echo false; fi)
        DEPLOY_TEST=$(if [[ "${{ github.event.inputs.namespace }}" == *Test ]]; then echo true; else echo false; fi)

        echo "::set-output name=push-qms::"$PUSH_QMS
        echo "::set-output name=push-theq::"$PUSH_THEQ
        echo "::set-output name=deploy-dev::"$DEPLOY_DEV
        echo "::set-output name=deploy-test::"$DEPLOY_TEST

  create-image-tags:
    name: Create Image Tags
    needs: parse-namespace
    runs-on: ubuntu-latest
    outputs:
      image-tags: ${{ steps.get-image-tags.outputs.image-tags }}
      push-qms: ${{ needs.parse-namespace.outputs.push-qms }}
      push-theq: ${{ needs.parse-namespace.outputs.push-theq }}

    steps:
    - name: Get Image Tags
      id: get-image-tags
      run: |
        IMAGE_TAGS=pr${{ github.event.inputs.pr-number }}
        echo Using tags: \"$IMAGE_TAGS\"
        echo "::set-output name=image-tags::$IMAGE_TAGS"

  ##### BUILD ######################################################################################

  appointment-frontend:
    name: appointment-frontend
    needs: create-image-tags
    uses: walter-moar/queue-management/.github/workflows/reusable-build-dockerfile.yaml@master
    secrets:
      artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      artifactory-registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
      artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      namespace-theq: ${{ secrets.NAMESPACE_THEQ }}
      namespace-theq-password: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}
      namespace-theq-username: ${{ secrets.NAMESPACE_THEQ_USERNAME }}
      namespace-qms: ${{ secrets.NAMESPACE_QMS }}
      namespace-qms-password: ${{ secrets.NAMESPACE_QMS_PASSWORD }}
      namespace-qms-username: ${{ secrets.NAMESPACE_QMS_USERNAME }}
      openshift-registry: ${{ secrets.OPENSHIFT_REGISTRY }}
    with:
      ref: refs/pull/${{ github.event.inputs.pr-number }}/head
      directory: appointment-frontend
      image-name: appointment-frontend
      image-tags: ${{ needs.create-image-tags.outputs.image-tags }}
      push-qms: ${{ needs.create-image-tags.outputs.push-qms == 'true' }}
      push-theq: ${{ needs.create-image-tags.outputs.push-theq == 'true' }}

  feedback-api:
    name: feedback-api
    needs: create-image-tags
    uses: walter-moar/queue-management/.github/workflows/reusable-build-s2i.yaml@master
    secrets:
      namespace-theq: ${{ secrets.NAMESPACE_THEQ }}
      namespace-theq-password: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}
      namespace-theq-username: ${{ secrets.NAMESPACE_THEQ_USERNAME }}
      namespace-qms: ${{ secrets.NAMESPACE_QMS }}
      namespace-qms-password: ${{ secrets.NAMESPACE_QMS_PASSWORD }}
      namespace-qms-username: ${{ secrets.NAMESPACE_QMS_USERNAME }}
      openshift-registry: ${{ secrets.OPENSHIFT_REGISTRY }}
    with:
      ref: refs/pull/${{ github.event.inputs.pr-number }}/head
      directory: feedback-api
      image-name: feedback-api
      image-tags: ${{ needs.create-image-tags.outputs.image-tags }}
      push-qms: ${{ needs.create-image-tags.outputs.push-qms == 'true' }}
      push-theq: ${{ needs.create-image-tags.outputs.push-theq == 'true' }}

  notifications-api:
    name: notifications-api
    needs: create-image-tags
    uses: walter-moar/queue-management/.github/workflows/reusable-build-s2i.yaml@master
    secrets:
      namespace-theq: ${{ secrets.NAMESPACE_THEQ }}
      namespace-theq-password: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}
      namespace-theq-username: ${{ secrets.NAMESPACE_THEQ_USERNAME }}
      namespace-qms: ${{ secrets.NAMESPACE_QMS }}
      namespace-qms-password: ${{ secrets.NAMESPACE_QMS_PASSWORD }}
      namespace-qms-username: ${{ secrets.NAMESPACE_QMS_USERNAME }}
      openshift-registry: ${{ secrets.OPENSHIFT_REGISTRY }}
    with:
      ref: refs/pull/${{ github.event.inputs.pr-number }}/head
      directory: notifications-api
      image-name: notifications-api
      image-tags: ${{ needs.create-image-tags.outputs.image-tags }}
      push-qms: ${{ needs.create-image-tags.outputs.push-qms == 'true' }}
      push-theq: ${{ needs.create-image-tags.outputs.push-theq == 'true' }}

  queue-management-api:
    name: queue-management-api
    needs: create-image-tags
    uses: walter-moar/queue-management/.github/workflows/reusable-build-s2i.yaml@master
    secrets:
      artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      artifactory-registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
      artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      namespace-theq: ${{ secrets.NAMESPACE_THEQ }}
      namespace-theq-password: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}
      namespace-theq-username: ${{ secrets.NAMESPACE_THEQ_USERNAME }}
      namespace-qms: ${{ secrets.NAMESPACE_QMS }}
      namespace-qms-password: ${{ secrets.NAMESPACE_QMS_PASSWORD }}
      namespace-qms-username: ${{ secrets.NAMESPACE_QMS_USERNAME }}
      openshift-registry: ${{ secrets.OPENSHIFT_REGISTRY }}
    with:
      ref: refs/pull/${{ github.event.inputs.pr-number }}/head
      directory: api
      image-name: queue-management-api
      image-tags: ${{ needs.create-image-tags.outputs.image-tags }}
      push-qms: ${{ needs.create-image-tags.outputs.push-qms == 'true' }}
      push-theq: ${{ needs.create-image-tags.outputs.push-theq == 'true' }}

  queue-management-frontend:
    name: queue-management-frontend
    needs: create-image-tags
    uses: walter-moar/queue-management/.github/workflows/reusable-build-dockerfile.yaml@master
    secrets:
      artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      artifactory-registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
      artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      namespace-theq: ${{ secrets.NAMESPACE_THEQ }}
      namespace-theq-password: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}
      namespace-theq-username: ${{ secrets.NAMESPACE_THEQ_USERNAME }}
      namespace-qms: ${{ secrets.NAMESPACE_QMS }}
      namespace-qms-password: ${{ secrets.NAMESPACE_QMS_PASSWORD }}
      namespace-qms-username: ${{ secrets.NAMESPACE_QMS_USERNAME }}
      openshift-registry: ${{ secrets.OPENSHIFT_REGISTRY }}
    with:
      ref: refs/pull/${{ github.event.inputs.pr-number }}/head
      directory: frontend
      image-name: queue-management-frontend
      image-tags: ${{ needs.create-image-tags.outputs.image-tags }}
      push-qms: ${{ needs.create-image-tags.outputs.push-qms == 'true' }}
      push-theq: ${{ needs.create-image-tags.outputs.push-theq == 'true' }}

  send-appointment-reminder-crond:
    name: send-appointment-reminder-crond
    needs: create-image-tags
    uses: walter-moar/queue-management/.github/workflows/reusable-build-dockerfile.yaml@master
    secrets:
      artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      artifactory-registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
      artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      namespace-theq: ${{ secrets.NAMESPACE_THEQ }}
      namespace-theq-password: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}
      namespace-theq-username: ${{ secrets.NAMESPACE_THEQ_USERNAME }}
      namespace-qms: ${{ secrets.NAMESPACE_QMS }}
      namespace-qms-password: ${{ secrets.NAMESPACE_QMS_PASSWORD }}
      namespace-qms-username: ${{ secrets.NAMESPACE_QMS_USERNAME }}
      openshift-registry: ${{ secrets.OPENSHIFT_REGISTRY }}
    with:
      ref: refs/pull/${{ github.event.inputs.pr-number }}/head
      directory: jobs/appointment_reminder
      image-name: send-appointment-reminder-crond
      image-tags: ${{ needs.create-image-tags.outputs.image-tags }}
      push-qms: ${{ needs.create-image-tags.outputs.push-qms == 'true' }}
      push-theq: ${{ needs.create-image-tags.outputs.push-theq == 'true' }}

  ##### DEPLOY ####################################################################################

  parse-environment:
    name: Get Environment
    needs: [appointment-frontend, feedback-api, notifications-api, queue-management-api, queue-management-frontend, send-appointment-reminder-crond]
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.parse.outputs.environment }}
      image-tags: ${{ needs.appointment-frontend.outputs.image-tags }}
      namespace: ${{ steps.parse.outputs.namespace }}
      token: ${{ steps.parse.outputs.token }}

    steps:
    - name: Parse Environment
      id: parse
      run: |
        ENVIRONMENT=$(echo ${{ github.event.inputs.namespace }} | cut -d' ' -f2 | tr '[:upper:]' '[:lower:]')
        echo "::set-output name=environment::$ENVIRONMENT"

        if [[ "${{ github.event.inputs.namespace }}" == QMS* ]]; then
          echo "::set-output name=namespace::${{ secrets.NAMESPACE_QMS }}"
          echo "::set-output name=token::${{ secrets.NAMESPACE_QMS_PASSWORD }}"
        else
          echo "::set-output name=namespace::${{ secrets.NAMESPACE_THEQ }}"
          echo "::set-output name=token::${{ secrets.NAMESPACE_THEQ_PASSWORD }}"
        fi

  tag:
    name: Tag
    needs: parse-environment
    uses: walter-moar/queue-management/.github/workflows/reusable-tag-image.yaml@master
    secrets:
      namespace: ${{ needs.parse-environment.outputs.namespace }}
      openshift-api: ${{ secrets.OPENSHIFT_API }}
      openshift-token: ${{ needs.parse-environment.outputs.token }}
    with:
      image-names: appointment-frontend feedback-api notifications-api queue-management-api queue-management-frontend send-appointment-reminder-crond
      tag-from: ${{ needs.parse-environment.outputs.image-tags }}
      tag-to: ${{ needs.parse-environment.outputs.environment }}
