name: Build Pull Request
on:
  workflow_dispatch:
    inputs:
      pr-number:
        description: Pull Request Number
        required: true

jobs:

  ##### SETUP ######################################################################################

  aside:
    name: Building refs/pull/${{ github.event.inputs.pr-number }}/head
    runs-on: ubuntu-latest

    steps:
    - name: echo
      run: echo Building for PR ${{ github.event.inputs.pr-number }}

  create-image-tags:
    name: Create Image Tags
    runs-on: ubuntu-latest
    outputs:
      image-tags: ${{ steps.get-image-tags.outputs.image-tags }}

    steps:
    - name: Get Image Tags
      id: get-image-tags
      run: |
        IMAGE_TAGS=pr${{ steps.get-image-tags.outputs.image-tags }}
        echo Using tags: \"$IMAGE_TAGS\"
        echo "::set-output name=image-tags::$IMAGE_TAGS"

  build:
    name: Dockerfile Build
    needs: create-image-tags
    runs-on: ubuntu-latest
#     outputs:
#       image-tags: ${{ steps.build-image.outputs.tags }}

    steps:
    - name: echo
      run: |
        echo ${{ github.event.inputs.pr-number }}
        echo refs/pull/${{ github.event.inputs.pr-number }}/head

    - name: Check out
      uses: actions/checkout@v2
      with:
          ref: refs/pull/${{ github.event.inputs.pr-number }}/head
          
    - name: meow
      run: |
        # ls -laR
        cat .github/workflows/README.md

#     - name: Login to Artifactory to Pull Images in Buildah Build
#       uses: redhat-actions/podman-login@v1
#       with:
#         registry: ${{ secrets.artifactory-registry }}
#         username: ${{ secrets.artifactory-username }}
#         password: ${{ secrets.artifactory-password }}

#     - name: Buildah Build
#       id: build-image
#       uses: redhat-actions/buildah-build@v2
#       with:
#         containerfiles: ${{ inputs.directory }}/Dockerfile
#         context: ${{ inputs.directory }}
#         image: ${{ inputs.image-name }}
#         tags: ${{ inputs.image-tags }}
