name: on-pr-merge
on:
  workflow_dispatch:

jobs:
  build-appointment-frontend:
    name: build-appointment-frontend
    runs-on: ubuntu-latest

    steps:
    - name: build
      shell: bash
      run: |
        echo Build complete

  build-api:
    name: build-api
    runs-on: ubuntu-latest

    steps:
    - name: build
      shell: bash
      run: |
        echo Build complete

  dev:
    name: deploy-dev
    needs: [build-appointment-frontend, build-api]
    environment: dev
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Deploy to dev complete
 
  test:
    name: deploy-test
    needs: dev
    environment: test
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Deploy to test complete
 

  prod:
    name: deploy-prod
    needs: test
    environment: prod
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Deploy to prod complete
 
