name: on-pr-merge
on:
  workflow_dispatch:

jobs:
  build-api:
    name: build-api
    runs-on: ubuntu-latest

    steps:
    - name: build
      shell: bash
      run: |
        echo Build complete

  build-appointment-frontend:
    name: build-appointment-frontend
    runs-on: ubuntu-latest

    steps:
    - name: build
      shell: bash
      run: |
        echo Build complete

  build-feedback-api:
    name: build-feedback-api
    runs-on: ubuntu-latest

    steps:
    - name: build
      shell: bash
      run: |
        echo Build complete

  build-frontend:
    name: build-frontend
    runs-on: ubuntu-latest

    steps:
    - name: build
      shell: bash
      run: |
        echo Build complete

  build-jobs-appointment-reminder:
    name: build-jobs-appointment-reminder
    runs-on: ubuntu-latest

    steps:
    - name: build
      shell: bash
      run: |
        echo Build complete

  build-notifications-api:
    name: build-notifications-api
    runs-on: ubuntu-latest

    steps:
    - name: build
      shell: bash
      run: |
        echo Build complete

  dev:
    name: deploy-dev
    needs: [build-api, build-appointment-frontend, build-feedback-api, build-frontend, build-jobs-appointment-reminder, build-notifications-api]
    environment: dev
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Deploy to dev complete
 
  test:
    name: deploy-test
    needs: dev
    environment: test
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Deploy to test complete
 

  prod:
    name: deploy-prod
    needs: test
    environment: prod
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Deploy to prod complete
 
