name: Queue Management
on:
  workflow_dispatch:

jobs:
  build-api:
    name: Build /api
    runs-on: ubuntu-latest

    steps:
    - name: build
      shell: bash
      run: |
        echo Build complete

  build-appointment-frontend:
    name: Build /appointment-frontend
    runs-on: ubuntu-latest

    steps:
    - name: build
      shell: bash
      run: |
        echo Build complete

  build-feedback-api:
    name: Build /feedback-api
    runs-on: ubuntu-latest

    steps:
    - name: build
      shell: bash
      run: |
        echo Build complete

  build-frontend:
    name: Build /frontend
    runs-on: ubuntu-latest

    steps:
    - name: build
      shell: bash
      run: |
        echo Build complete

  build-jobs-appointment-reminder:
    name: Build /jobs/appointment-reminder
    runs-on: ubuntu-latest

    steps:
    - name: build
      shell: bash
      run: |
        echo Build complete

  build-notifications-api:
    name: Build /notifications-api
    runs-on: ubuntu-latest

    steps:
    - name: build
      shell: bash
      run: |
        echo Build complete

  deploy-theq-dev:
    name: Deploy to TheQ dev
    needs: [build-api, build-appointment-frontend, build-feedback-api, build-frontend, build-jobs-appointment-reminder, build-notifications-api]
    environment: theq-dev
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Deploy to The Q dev complete
 
  deploy-theq-test:
    name: Deploy to TheQ test
    needs: deploy-theq-dev
    environment: theq-test
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Deploy to The Q test complete
 
  deploy-theq-prod:
    name: Deploy to TheQ prod
    needs: deploy-theq-test
    environment: theq-prod
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Deploy to The Q prod complete
 
  deploy-qms-dev:
    name: Deploy to QMS dev
    needs: [build-api, build-appointment-frontend, build-feedback-api, build-frontend, build-jobs-appointment-reminder, build-notifications-api]
    environment: qms-dev
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Deploy to QMS dev complete
 
  deploy-qms-test:
    name: Deploy to QMS test
    needs: deploy-qms-dev
    environment: qms-test
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Deploy to QMS test complete
 
  deploy-qms-prod:
    name: Deploy to QMS prod
    needs: deploy-qms-test
    environment: qms-prod
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Deploy to QMS prod complete
 
