name: Parent
on:
  workflow_dispatch:

jobs:
  parent:
    name: Parent
    runs-on: ubuntu-latest

    steps:
    - name: debug
      shell: bash
      run: |
        ls -la /home/runner/work/queue-management

    - name: child
      uses: ./.github/workflows/child

    - name: echo
      shell: bash
      run: |
        echo Hello
