on:
  pull_request:
    paths:
      - feedback-api/**

jobs:
  feedback-api-pylint:
    name: Feedback API Pylint
    uses: walter-moar/queue-management/.github/workflows/reusable-pylint.yaml@master
    with:
      continue-on-error: true
      directory: feedback-api
      target: "*.py src"

  feedback-api-flake8:
    name: Feedback API Flake8
    uses: walter-moar/queue-management/.github/workflows/reusable-flake8.yaml@master
    with:
      continue-on-error: true
      directory: feedback-api
