on:
  pull_request:
    paths:
      - api/**

jobs:
  queue-management-api-pylint:
    name: Queue Management API Pylint
    uses: walter-moar/queue-management/.github/workflows/reusable-pylint.yaml@master
    with:
      continue-on-error: true
      directory: api
      target: "*.py app"

  queue-management-api-flake8:
    name: Queue Management API Flake8
    uses: walter-moar/queue-management/.github/workflows/reusable-flake8.yaml@master
    with:
      continue-on-error: true
      directory: api
