name: Queue Management
concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true
on:
  workflow_dispatch:

jobs:

  ##### SETUP ######################################################################################

  newman-tests:
    name: newman
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: tests
      run: |
        cd api/postman
        npm init -y
        npm install newman
        echo 1: ${USERID} 2: ${PASSWORD} 3: ${USERID_NONQTXN} 4: ${PASSWORD_NONQTXN} 5: ${CLIENT_SECRET} 6: ${API_URL} 7: ${AUTH_URL} 8: ${CLIENTID} 9: ${REALM} 10: ${PUBLIC_API_URL} 11: ${PUBLIC_USERID} 12: ${PASSWORD_PUBLIC_USER}
        exit 1
        #./node_modules/newman/bin/newman.js run API_Test_TheQ_Booking.json --delay-request 250 -e postman_env.json --global-var 'userid=${USERID}' --global-var 'password=${PASSWORD}' --global-var 'userid_nonqtxn=${USERID_NONQTXN}' --global-var 'password_nonqtxn=${PASSWORD_NONQTXN}' --global-var 'client_secret=${CLIENT_SECRET}' --global-var 'url=${API_URL}' --global-var 'auth_url=${AUTH_URL}' --global-var 'clientid=${CLIENTID}' --global-var 'realm=${REALM}' --global-var public_url=${PUBLIC_API_URL} --global-var public_user_id=${PUBLIC_USERID} --global-var public_user_password=${PASSWORD_PUBLIC_USER}

  create-image-tags:
    name: Create Image Tags
    runs-on: ubuntu-latest
    outputs:
      image-tags: ${{ steps.get-image-tags.outputs.image-tags }}

    steps:
    - name: Get Image Tags
      id: get-image-tags
      run: |
        IMAGE_TAGS=$GITHUB_REPOSITORY_OWNER-$GITHUB_REF_NAME
        if [ $IMAGE_TAGS == "bcgov-master" ]; then
          # Will eventually change this to "latest" but for now don't
          # replace the image that is created by the Jenkins build.
          IMAGE_TAGS=actions-latest
        fi
        echo Using tags: \"$IMAGE_TAGS\"
        echo "::set-output name=image-tags::$IMAGE_TAGS"
          
  ##### BUILD ######################################################################################

  build-api:
    name: /api
    needs: create-image-tags
    uses: walter-moar/queue-management/.github/workflows/reusable-build-s2i.yaml@master
    secrets:
      artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      artifactory-registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
      artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      namespace-theq: ${{ secrets.NAMESPACE_THEQ }}
      namespace-theq-password: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}
      namespace-theq-username: ${{ secrets.NAMESPACE_THEQ_USERNAME }}
      namespace-qms: ${{ secrets.NAMESPACE_QMS }}
      namespace-qms-password: ${{ secrets.NAMESPACE_QMS_PASSWORD }}
      namespace-qms-username: ${{ secrets.NAMESPACE_QMS_USERNAME }}
      openshift-registry: ${{ secrets.OPENSHIFT_REGISTRY }}
    with:
      directory: appointment-frontend
      image-name: appointment-frontend
      image-tags: ${{ needs.create-image-tags.outputs.image-tags }}

  build-appointment-frontend:
    name: /appointment-frontend
    needs: create-image-tags
    uses: walter-moar/queue-management/.github/workflows/reusable-build-dockerfile.yaml@master
    secrets:
      artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      artifactory-registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
      artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      namespace-theq: ${{ secrets.NAMESPACE_THEQ }}
      namespace-theq-password: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}
      namespace-theq-username: ${{ secrets.NAMESPACE_THEQ_USERNAME }}
      namespace-qms: ${{ secrets.NAMESPACE_QMS }}
      namespace-qms-password: ${{ secrets.NAMESPACE_QMS_PASSWORD }}
      namespace-qms-username: ${{ secrets.NAMESPACE_QMS_USERNAME }}
      openshift-registry: ${{ secrets.OPENSHIFT_REGISTRY }}
    with:
      directory: appointment-frontend
      image-name: appointment-frontend
      image-tags: ${{ needs.create-image-tags.outputs.image-tags }}

  build-feedback-api:
    name: /feedback-api
    needs: create-image-tags
    uses: walter-moar/queue-management/.github/workflows/reusable-build-s2i.yaml@master
    secrets:
      artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      artifactory-registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
      artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      namespace-theq: ${{ secrets.NAMESPACE_THEQ }}
      namespace-theq-password: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}
      namespace-theq-username: ${{ secrets.NAMESPACE_THEQ_USERNAME }}
      namespace-qms: ${{ secrets.NAMESPACE_QMS }}
      namespace-qms-password: ${{ secrets.NAMESPACE_QMS_PASSWORD }}
      namespace-qms-username: ${{ secrets.NAMESPACE_QMS_USERNAME }}
      openshift-registry: ${{ secrets.OPENSHIFT_REGISTRY }}
    with:
      directory: appointment-frontend
      image-name: appointment-frontend
      image-tags: ${{ needs.create-image-tags.outputs.image-tags }}

  build-frontend:
    name: /frontend
    needs: create-image-tags
    uses: walter-moar/queue-management/.github/workflows/reusable-build-dockerfile.yaml@master
    secrets:
      artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      artifactory-registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
      artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      namespace-theq: ${{ secrets.NAMESPACE_THEQ }}
      namespace-theq-password: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}
      namespace-theq-username: ${{ secrets.NAMESPACE_THEQ_USERNAME }}
      namespace-qms: ${{ secrets.NAMESPACE_QMS }}
      namespace-qms-password: ${{ secrets.NAMESPACE_QMS_PASSWORD }}
      namespace-qms-username: ${{ secrets.NAMESPACE_QMS_USERNAME }}
      openshift-registry: ${{ secrets.OPENSHIFT_REGISTRY }}
    with:
      directory: appointment-frontend
      image-name: appointment-frontend
      image-tags: ${{ needs.create-image-tags.outputs.image-tags }}

  build-jobs-appointment-reminder:
    name: /jobs/appointment-reminder
    needs: create-image-tags
    uses: walter-moar/queue-management/.github/workflows/reusable-build-dockerfile.yaml@master
    secrets:
      artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      artifactory-registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
      artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      namespace-theq: ${{ secrets.NAMESPACE_THEQ }}
      namespace-theq-password: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}
      namespace-theq-username: ${{ secrets.NAMESPACE_THEQ_USERNAME }}
      namespace-qms: ${{ secrets.NAMESPACE_QMS }}
      namespace-qms-password: ${{ secrets.NAMESPACE_QMS_PASSWORD }}
      namespace-qms-username: ${{ secrets.NAMESPACE_QMS_USERNAME }}
      openshift-registry: ${{ secrets.OPENSHIFT_REGISTRY }}
    with:
      directory: appointment-frontend
      image-name: appointment-frontend
      image-tags: ${{ needs.create-image-tags.outputs.image-tags }}

  build-notifications-api:
    name: /notifications-api
    needs: create-image-tags
    uses: walter-moar/queue-management/.github/workflows/reusable-build-s2i.yaml@master
    secrets:
      artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      artifactory-registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
      artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      namespace-theq: ${{ secrets.NAMESPACE_THEQ }}
      namespace-theq-password: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}
      namespace-theq-username: ${{ secrets.NAMESPACE_THEQ_USERNAME }}
      namespace-qms: ${{ secrets.NAMESPACE_QMS }}
      namespace-qms-password: ${{ secrets.NAMESPACE_QMS_PASSWORD }}
      namespace-qms-username: ${{ secrets.NAMESPACE_QMS_USERNAME }}
      openshift-registry: ${{ secrets.OPENSHIFT_REGISTRY }}
    with:
      directory: appointment-frontend
      image-name: appointment-frontend
      image-tags: ${{ needs.create-image-tags.outputs.image-tags }}

  ##### DEPLOY THE Q ###############################################################################

  approve-theq-dev:
    name: Approve Deploy to The Q dev
    needs: [build-api, build-appointment-frontend, build-feedback-api, build-frontend, build-jobs-appointment-reminder, build-notifications-api]
    environment: theq-dev
    outputs:
      image-tags: ${{ needs.build-api.outputs.image-tags }}

    runs-on: ubuntu-latest
    steps:
      - name: Deployment Approval
        run: echo Approved

  tag-theq-dev:
    name: Tag The Q dev
    needs: approve-theq-dev
    uses: walter-moar/queue-management/.github/workflows/reusable-tag-image.yaml@master
    secrets:
      namespace: ${{ secrets.NAMESPACE_THEQ }}
      openshift-api: ${{ secrets.OPENSHIFT_API }}
      openshift-token: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}
    with:
      image-names: appointment-frontend
      tag-from: ${{ needs.approve-theq-dev.outputs.image-tags }}
      tag-to: dev

  newman-theq:
    name: Newman tests in TheQ dev
    needs: tag-theq-dev
    outputs:
      image-tags: ${{ needs.tag-theq-dev.outputs.tag-from }}

    runs-on: ubuntu-latest
    steps:
      - name: newman
        run: echo Newman tests complete

  approve-theq-test:
    name: Approve Deploy to The Q test
    needs: newman-theq
    environment: theq-test
    outputs:
      image-tags: ${{ needs.newman-theq.outputs.image-tags }}

    runs-on: ubuntu-latest
    steps:
      - name: Deployment Approval
        run: echo Approved

  tag-theq-test:
    name: Tag The Q test
    needs: approve-theq-test
    uses: walter-moar/queue-management/.github/workflows/reusable-tag-image.yaml@master
    secrets:
      namespace: ${{ secrets.NAMESPACE_THEQ }}
      openshift-api: ${{ secrets.OPENSHIFT_API }}
      openshift-token: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}
    with:
      image-names: appointment-frontend
      tag-from: ${{ needs.approve-theq-test.outputs.image-tags }}
      tag-to: test

  approve-theq-prod:
    name: Approve Deploy to The Q prod
    needs: tag-theq-test
    environment: theq-prod
    outputs:
      image-tags: ${{ needs.tag-theq-test.outputs.tag-from }}

    runs-on: ubuntu-latest
    steps:
      - name: Deployment Approval
        run: echo Approved

  tag-theq-prod:
    name: Tag The Q prod
    needs: approve-theq-prod
    uses: walter-moar/queue-management/.github/workflows/reusable-tag-image.yaml@master
    secrets:
      namespace: ${{ secrets.NAMESPACE_THEQ }}
      openshift-api: ${{ secrets.OPENSHIFT_API }}
      openshift-token: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}
    with:
      image-names: appointment-frontend
      tag-from: ${{ needs.approve-theq-prod.outputs.image-tags }}
      tag-to: prod

  ##### DEPLOY QMS #################################################################################

  approve-qms-dev:
    name: Approve Deploy to QMS dev
    needs: [build-api, build-appointment-frontend, build-feedback-api, build-frontend, build-jobs-appointment-reminder, build-notifications-api]
    environment: qms-dev
    outputs:
      image-tags: ${{ needs.build-api.outputs.image-tags }}

    runs-on: ubuntu-latest
    steps:
      - name: Deployment Approval
        run: echo Approved

  tag-qms-dev:
    name: Tag QMS dev
    needs: approve-qms-dev
    uses: walter-moar/queue-management/.github/workflows/reusable-tag-image.yaml@master
    secrets:
      namespace: ${{ secrets.NAMESPACE_QMS }}
      openshift-api: ${{ secrets.OPENSHIFT_API }}
      openshift-token: ${{ secrets.NAMESPACE_QMS_PASSWORD }}
    with:
      image-names: appointment-frontend
      tag-from: ${{ needs.approve-qms-dev.outputs.image-tags }}
      tag-to: dev

  newman-qms:
    name: Newman tests in QMS dev
    needs: tag-qms-dev
    outputs:
      image-tags: ${{ needs.tag-qms-dev.outputs.tag-from }}

    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo Newman tests complete

  approve-qms-test:
    name: Approve Deploy to QMS test
    needs: newman-qms
    environment: qms-test
    outputs:
      image-tags: ${{ needs.newman-qms.outputs.image-tags }}

    runs-on: ubuntu-latest
    steps:
      - name: Deployment Approval
        run: echo Approved

  tag-qms-test:
    name: Tag QMS test
    needs: approve-qms-test
    uses: walter-moar/queue-management/.github/workflows/reusable-tag-image.yaml@master
    secrets:
      namespace: ${{ secrets.NAMESPACE_THEQ }}
      openshift-api: ${{ secrets.OPENSHIFT_API }}
      openshift-token: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}
    with:
      image-names: appointment-frontend
      tag-from: ${{ needs.approve-qms-test.outputs.image-tags }}
      tag-to: test

  approve-qms-prod:
    name: Approve Deploy to QMS prod
    needs: tag-qms-test
    environment: qms-prod
    outputs:
      image-tags: ${{ needs.tag-qms-test.outputs.tag-from }}

    runs-on: ubuntu-latest
    steps:
      - name: Deployment Approval
        run: echo Approved

  tag-qms-prod:
    name: Tag QMS prod
    needs: approve-qms-prod
    uses: walter-moar/queue-management/.github/workflows/reusable-tag-image.yaml@master
    secrets:
      namespace: ${{ secrets.NAMESPACE_THEQ }}
      openshift-api: ${{ secrets.OPENSHIFT_API }}
      openshift-token: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}
    with:
      image-names: appointment-frontend
      tag-from: ${{ needs.approve-qms-prod.outputs.image-tags }}
      tag-to: prod
