name: Queue Management
concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true
on:
  workflow_dispatch:

jobs:
  build-api:
    name: Build /api
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Get Image Tag
      id: get-image-tag
      shell: bash
      run: |
        IMAGE_TAG=$GITHUB_REPOSITORY_OWNER-$GITHUB_REF_NAME
        if [ $IMAGE_TAG == "bcgov-master" ]; then
          # Will eventually change this to "latest" but for now don't
          # replace the image that is created by the Jenkins build.
          IMAGE_TAG=actions-latest
        fi
        echo "::set-output name=image-tag::$IMAGE_TAG"

#     - name: Artifactory Credentials
#       shell: bash
#       run: |
#         echo "AF_USERID=${{ secrets.ARTIFACTORY_USERNAME }}" >> $GITHUB_ENV
#         echo "AF_PASSWD=${{ secrets.ARTIFACTORY_PASSWORD }}" >> $GITHUB_ENV

    - name: s2i Build
      id: build_image
      uses: redhat-actions/s2i-build@v2
      with:
        builder_image: registry.access.redhat.com/ubi8/python-38:latest
        env_vars: |-
          AF_USERID=${{ secrets.ARTIFACTORY_USERNAME }}
          AF_PASSWD=${{ secrets.ARTIFACTORY_PASSWORD }}
        image: queue-management-api
        path_context: ./api
        tags: ${{ steps.get-image-tag.outputs.image-tag }}

# Push Image to Quay registry
#     - name: Push To Quay Action
#       uses: redhat-actions/push-to-registry@v2
#       with:
#         image: ${{ steps.build_image.outputs.image }}
#         tags: ${{ steps.build_image.outputs.tags }}
#         registry: quay.io/${{ secrets.QUAY_USERNAME }}
#         username: ${{ secrets.QUAY_USERNAME }}
#         password: ${{ secrets.QUAY_PASSWORD }}

  build-appointment-frontend:
    name: Build /appointment-frontend
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    #- name: build
    #  uses: ./.github/workflows/reusable-build-dockerfile.yaml
    #  with:
    #    directory: appointment-frontend
    #    image-name: appointment-frontend
    # Can't get above to work, just copy it all and figure out later.

    - name: Login to Artifactory to Pull Images in build-image
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
        username: ${{ secrets.ARTIFACTORY_USERNAME }}
        password: ${{ secrets.ARTIFACTORY_PASSWORD }}

    - name: Get Image Tag
      id: get-image-tag
      shell: bash
      run: |
        IMAGE_TAG=$GITHUB_REPOSITORY_OWNER-$GITHUB_REF_NAME
        if [ $IMAGE_TAG == "bcgov-master" ]; then
          # Will eventually change this to "latest" but for now don't
          # replace the image that is created by the Jenkins build.
          IMAGE_TAG=actions-latest
        fi
        echo "::set-output name=image-tag::$IMAGE_TAG"

    - name: Buildah Action
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        containerfiles: appointment-frontend/Dockerfile
        context: appointment-frontend
        image: appointment-frontend
        tags: ${{ steps.get-image-tag.outputs.image-tag }}

    - name: Push Image to The Q
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ secrets.OPENSHIFT_REGISTRY }}/${{ secrets.NAMESPACE_THEQ }}
        username: ${{ secrets.NAMESPACE_THEQ_USERNAME }}
        password: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}

    - name: Push Image to QMS
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ secrets.OPENSHIFT_REGISTRY }}/${{ secrets.NAMESPACE_QMS }}
        username: ${{ secrets.NAMESPACE_QMS_USERNAME }}
        password: ${{ secrets.NAMESPACE_QMS_PASSWORD }}

  build-feedback-api:
    name: Build /feedback-api
    runs-on: ubuntu-latest

    steps:
    - name: build
      shell: bash
      run: |
        echo Build complete

  build-frontend:
    name: Build /frontend
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Login to Artifactory to Pull Images in build-image
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
        username: ${{ secrets.ARTIFACTORY_USERNAME }}
        password: ${{ secrets.ARTIFACTORY_PASSWORD }}

    - name: Get Image Tag
      id: get-image-tag
      shell: bash
      run: |
        IMAGE_TAG=$GITHUB_REPOSITORY_OWNER-$GITHUB_REF_NAME
        if [ $IMAGE_TAG == "bcgov-master" ]; then
          # Will eventually change this to "latest" but for now don't
          # replace the image that is created by the Jenkins build.
          IMAGE_TAG=actions-latest
        fi
        echo "::set-output name=image-tag::$IMAGE_TAG"

    - name: Buildah Action
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        containerfiles: frontend/Dockerfile
        context: frontend
        image: queue-management-frontend
        tags: ${{ steps.get-image-tag.outputs.image-tag }}

    - name: Push Image to The Q
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ secrets.OPENSHIFT_REGISTRY }}/${{ secrets.NAMESPACE_THEQ }}
        username: ${{ secrets.NAMESPACE_THEQ_USERNAME }}
        password: ${{ secrets.NAMESPACE_THEQ_PASSWORD }}

    - name: Push Image to QMS
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ secrets.OPENSHIFT_REGISTRY }}/${{ secrets.NAMESPACE_QMS }}
        username: ${{ secrets.NAMESPACE_QMS_USERNAME }}
        password: ${{ secrets.NAMESPACE_QMS_PASSWORD }}

  build-jobs-appointment-reminder:
    name: Build /jobs/appointment-reminder
    runs-on: ubuntu-latest

    steps:
    - name: build
      shell: bash
      run: |
        echo Build complete

  build-notifications-api:
    name: Build /notifications-api
    runs-on: ubuntu-latest

    steps:
    - name: build
      shell: bash
      run: |
        echo Build complete

  deploy-theq-dev:
    name: Deploy to TheQ dev
    needs: [build-api, build-appointment-frontend, build-feedback-api, build-frontend, build-jobs-appointment-reminder, build-notifications-api]
    environment: theq-dev
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Deploy complete
 
  newman-theq-dev:
    name: Newman tests in TheQ dev
    needs: deploy-theq-dev
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Newman tests complete
 
  deploy-theq-test:
    name: Deploy to TheQ test
    needs: newman-theq-dev
    environment: theq-test
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Deploy complete
 
  deploy-theq-prod:
    name: Deploy to TheQ prod
    needs: deploy-theq-test
    environment: theq-prod
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Deploy complete
 
  deploy-qms-dev:
    name: Deploy to QMS dev
    needs: [build-api, build-appointment-frontend, build-feedback-api, build-frontend, build-jobs-appointment-reminder, build-notifications-api]
    environment: qms-dev
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Deploy complete
 
  newman-qms-dev:
    name: Newman tests in QMS dev
    needs: deploy-qms-dev
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Newman tests complete
 
  deploy-qms-test:
    name: Deploy to QMS test
    needs: newman-qms-dev
    environment: qms-test
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Deploy complete
 
  deploy-qms-prod:
    name: Deploy to QMS prod
    needs: deploy-qms-test
    environment: qms-prod
  
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run: |
          echo Deploy complete
 
