name: Queue Management
concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true
on:
  workflow_dispatch:

jobs:

  ##### SETUP ######################################################################################

  create-image-tags:
    name: Create Image Tags
    runs-on: ubuntu-latest
    outputs:
      image-tags: ${{ steps.get-image-tags.outputs.image-tags }}

    steps:
    - name: Get Image Tags
      id: get-image-tags
      run: |
        IMAGE_TAGS=$GITHUB_REPOSITORY_OWNER-$GITHUB_REF_NAME
        if [ $IMAGE_TAGS == "bcgov-master" ]; then
          # Will eventually change this to "latest" but for now don't
          # replace the image that is created by the Jenkins build.
          IMAGE_TAGS=latest-github-actions
        fi
        echo IMAGE_TAGS:$IMAGE_TAGS
        echo "::set-output name=image-tags::$IMAGE_TAGS"

  ##### BUILD ######################################################################################

  appointment-frontend:
    name: appointment-frontend
    needs: create-image-tags
    uses: walter-moar/queue-management/.github/workflows/reusable-build-dockerfile.yaml@master
    secrets:
      artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      artifactory-registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
      artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      namespace-theq: ${{ secrets.LICENCE_PLATE_THEQ }}-tools
      namespace-theq-password: ${{ secrets.SA_PASSWORD_THEQ_TOOLS }}
      namespace-theq-username: ${{ secrets.SA_USERNAME }}
      namespace-qms: ${{ secrets.LICENCE_PLATE_QMS }}-tools
      namespace-qms-password: ${{ secrets.SA_PASSWORD_QMS_TOOLS }}
      namespace-qms-username: ${{ secrets.SA_USERNAME }}
      openshift-registry: ${{ secrets.OPENSHIFT_REGISTRY }}
    with:
      directory: appointment-frontend
      image-name: appointment-frontend
      image-tags: ${{ needs.create-image-tags.outputs.image-tags }}

  feedback-api:
    name: feedback-api
    needs: create-image-tags
    uses: walter-moar/queue-management/.github/workflows/reusable-build-s2i.yaml@master
    secrets:
      namespace-theq: ${{ secrets.LICENCE_PLATE_THEQ }}-tools
      namespace-theq-password: ${{ secrets.SA_PASSWORD_THEQ_TOOLS }}
      namespace-theq-username: ${{ secrets.SA_USERNAME }}
      namespace-qms: ${{ secrets.LICENCE_PLATE_QMS }}-tools
      namespace-qms-password: ${{ secrets.SA_PASSWORD_QMS_TOOLS }}
      namespace-qms-username: ${{ secrets.SA_USERNAME }}
      openshift-registry: ${{ secrets.OPENSHIFT_REGISTRY }}
    with:
      directory: feedback-api
      image-name: feedback-api
      image-tags: ${{ needs.create-image-tags.outputs.image-tags }}

  notifications-api:
    name: notifications-api
    needs: create-image-tags
    uses: walter-moar/queue-management/.github/workflows/reusable-build-s2i.yaml@master
    secrets:
      namespace-theq: ${{ secrets.LICENCE_PLATE_THEQ }}-tools
      namespace-theq-password: ${{ secrets.SA_PASSWORD_THEQ_TOOLS }}
      namespace-theq-username: ${{ secrets.SA_USERNAME }}
      namespace-qms: ${{ secrets.LICENCE_PLATE_QMS }}-tools
      namespace-qms-password: ${{ secrets.SA_PASSWORD_QMS_TOOLS }}
      namespace-qms-username: ${{ secrets.SA_USERNAME }}
      openshift-registry: ${{ secrets.OPENSHIFT_REGISTRY }}
    with:
      directory: notifications-api
      image-name: notifications-api
      image-tags: ${{ needs.create-image-tags.outputs.image-tags }}

  queue-management-api:
    name: queue-management-api
    needs: create-image-tags
    uses: walter-moar/queue-management/.github/workflows/reusable-build-s2i.yaml@master
    secrets:
      artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      artifactory-registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
      artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      namespace-theq: ${{ secrets.LICENCE_PLATE_THEQ }}-tools
      namespace-theq-password: ${{ secrets.SA_PASSWORD_THEQ_TOOLS }}
      namespace-theq-username: ${{ secrets.SA_USERNAME }}
      namespace-qms: ${{ secrets.LICENCE_PLATE_QMS }}-tools
      namespace-qms-password: ${{ secrets.SA_PASSWORD_QMS_TOOLS }}
      namespace-qms-username: ${{ secrets.SA_USERNAME }}
      openshift-registry: ${{ secrets.OPENSHIFT_REGISTRY }}
    with:
      directory: api
      image-name: queue-management-api
      image-tags: ${{ needs.create-image-tags.outputs.image-tags }}

  queue-management-frontend:
    name: queue-management-frontend
    needs: create-image-tags
    uses: walter-moar/queue-management/.github/workflows/reusable-build-dockerfile.yaml@master
    secrets:
      artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      artifactory-registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
      artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      namespace-theq: ${{ secrets.LICENCE_PLATE_THEQ }}-tools
      namespace-theq-password: ${{ secrets.SA_PASSWORD_THEQ_TOOLS }}
      namespace-theq-username: ${{ secrets.SA_USERNAME }}
      namespace-qms: ${{ secrets.LICENCE_PLATE_QMS }}-tools
      namespace-qms-password: ${{ secrets.SA_PASSWORD_QMS_TOOLS }}
      namespace-qms-username: ${{ secrets.SA_USERNAME }}
      openshift-registry: ${{ secrets.OPENSHIFT_REGISTRY }}
    with:
      directory: frontend
      image-name: queue-management-frontend
      image-tags: ${{ needs.create-image-tags.outputs.image-tags }}

  send-appointment-reminder-crond:
    name: send-appointment-reminder-crond
    needs: create-image-tags
    uses: walter-moar/queue-management/.github/workflows/reusable-build-dockerfile.yaml@master
    secrets:
      artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      artifactory-registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
      artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      namespace-theq: ${{ secrets.LICENCE_PLATE_THEQ }}-tools
      namespace-theq-password: ${{ secrets.SA_PASSWORD_THEQ_TOOLS }}
      namespace-theq-username: ${{ secrets.SA_USERNAME }}
      namespace-qms: ${{ secrets.LICENCE_PLATE_QMS }}-tools
      namespace-qms-password: ${{ secrets.SA_PASSWORD_QMS_TOOLS }}
      namespace-qms-username: ${{ secrets.SA_USERNAME }}
      openshift-registry: ${{ secrets.OPENSHIFT_REGISTRY }}
    with:
      directory: jobs/appointment_reminder
      image-name: send-appointment-reminder-crond
      image-tags: ${{ needs.create-image-tags.outputs.image-tags }}

  ##### DEPLOY THE Q ###############################################################################

  approve-theq-dev:
    name: Approve Deploy to The Q Dev
    needs: [appointment-frontend, feedback-api, notifications-api, queue-management-api, queue-management-frontend, send-appointment-reminder-crond]
    environment: The Q Dev
    runs-on: ubuntu-latest

    steps:
      - name: Deployment Approval
        run: echo Approved

  tag-theq-dev:
    name: Tag The Q Dev
    needs: [create-image-tags, approve-theq-dev]
    uses: walter-moar/queue-management/.github/workflows/reusable-tag-image.yaml@master
    secrets:
      licence-plate: ${{ secrets.LICENCE_PLATE_THEQ }}
      openshift-api: ${{ secrets.OPENSHIFT_API }}
      token: ${{ secrets.SA_PASSWORD_THEQ_TOOLS }}
    with:
      image-names: appointment-frontend feedback-api notifications-api queue-management-api queue-management-frontend send-appointment-reminder-crond
      tag-from: ${{ needs.create-image-tags.outputs.image-tags }}
      tag-to: dev

  wait-for-rollouts:
    name: Wait for Rollouts
    needs: tag-theq-dev
    uses: walter-moar/queue-management/.github/workflows/reusable-wait-for-rollouts.yaml@master
    secrets:
      licence-plate: ${{ secrets.LICENCE_PLATE_THEQ }}
      openshift-api: ${{ secrets.OPENSHIFT_API }}
      token: ${{ secrets.SA_PASSWORD_THEQ_DEV }}
    with:
      image-names: appointment-nginx-frontend feedback-api notifications-api queue-management-api queue-management-nginx-frontend send-appointment-reminder-crond-${{ needs.parse-inputs.outputs.environment }}
      tag-to: dev

  newman-theq:
    name: Newman Tests in The Q Dev
    needs: wait-for-rollouts
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: NPM Install
      run: |
        cd api/postman
        npm install newman

    - name: Run Newman Tests
      run: |
        cd api/postman
        node_modules/newman/bin/newman.js run API_Test_TheQ_Booking.json \
          -e postman_env.json \
          --delay-request 250 \
          --global-var 'auth_url=${{ secrets.POSTMAN_AUTH_URL }}' \
          --global-var 'clientid=${{ secrets.POSTMAN_CLIENTID }}' \
          --global-var 'client_secret=${{ secrets.POSTMAN_CLIENT_SECRET }}' \
          --global-var 'password=${{ secrets.POSTMAN_PASSWORD }}' \
          --global-var 'password_nonqtxn=${{ secrets.POSTMAN_PASSWORD_NONQTXN }}' \
          --global-var 'public_url=${{ secrets.POSTMAN_PUBLIC_API_URL }}' \
          --global-var 'public_user_id=${{ secrets.POSTMAN_PUBLIC_USERID }}' \
          --global-var 'public_user_password=${{ secrets.POSTMAN_PASSWORD_PUBLIC_USER }}' \
          --global-var 'realm=${{ secrets.POSTMAN_REALM }}' \
          --global-var 'url=${{ secrets.POSTMAN_API_URL }}' \
          --global-var 'userid=${{ secrets.POSTMAN_USERID }}' \
          --global-var 'userid_nonqtxn=${{ secrets.POSTMAN_USERID_NONQTXN }}'

  owasp-staff:
    name: OWASP ZAP Scan of The Q Dev
    needs: wait-for-rollouts
    runs-on: ubuntu-latest

    steps:
      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          allow_issue_writing: false
          target: ${{ secrets.ZAP_STAFFURL }}

      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: OWASP ZAP - Staff Front End Report
          path: report_html.html

        # This doesn't work - the new zap_scan file isn't marked as complete yet so can't be GETted, let alone deleted.
#       - name: Delete Default Report Artifacts
#         run: |
#           for url in $(curl --no-progress-meter -H "Accept: application/vnd.github.v3+json" \
#             https://api.github.com/repos/walter-moar/queue-management/actions/artifacts | \
#             jq -r '.artifacts[] | select(.name="zap_scan") | .url')
#           do
#             echo Deleting $url
#             curl --no-progress-meter -X DELETE -H "Accept: application/vnd.github.v3+json" \
#               --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' $url
#           done

  owasp-appointment:
    name: OWASP ZAP Scan of Appointments Dev
    needs: wait-for-rollouts
    runs-on: ubuntu-latest

    steps:
      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          allow_issue_writing: false
          target: ${{ secrets.ZAP_APPTMNTURL }}

      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: OWASP ZAP - Appointment Front End Report
          path: report_html.html

#       - name: Delete Default Report Artifacts
#         run: |
#           for url in $(curl --no-progress-meter -H "Accept: application/vnd.github.v3+json" \
#             https://api.github.com/repos/walter-moar/queue-management/actions/artifacts | \
#             jq -r '.artifacts[] | select(.name="zap_scan") | .url')
#           do
#             echo Deleting $url
#             curl --no-progress-meter -X DELETE -H "Accept: application/vnd.github.v3+json" \
#               --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' $url
#           done

  approve-theq-test:
    name: Approve Deploy to The Q Test
    needs: [newman-theq, owasp-staff, owasp-appointment]
    environment: The Q Test
    runs-on: ubuntu-latest

    steps:
      - name: Deployment Approval
        run: echo Approved

  tag-theq-test:
    name: Tag The Q Test
    needs: [create-image-tags, approve-theq-test]
    uses: walter-moar/queue-management/.github/workflows/reusable-tag-image.yaml@master
    secrets:
      licence-plate: ${{ secrets.LICENCE_PLATE_THEQ }}
      openshift-api: ${{ secrets.OPENSHIFT_API }}
      token: ${{ secrets.SA_PASSWORD_THEQ_TOOLS }}
    with:
      image-names: appointment-frontend feedback-api notifications-api queue-management-api queue-management-frontend send-appointment-reminder-crond
      tag-from: ${{ needs.create-image-tags.outputs.image-tags }}
      tag-to: test

  approve-theq-prod:
    name: Approve Deploy to The Q Prod
    needs: tag-theq-test
    environment: The Q Prod
    runs-on: ubuntu-latest

    steps:
      - name: Deployment Approval
        run: echo Approved

  tag-theq-prod:
    name: Tag The Q Prod
    needs: approve-theq-prod
    uses: walter-moar/queue-management/.github/workflows/reusable-tag-image.yaml@master
    secrets:
      licence-plate: ${{ secrets.LICENCE_PLATE_THEQ }}
      openshift-api: ${{ secrets.OPENSHIFT_API }}
      token: ${{ secrets.SA_PASSWORD_THEQ_TOOLS }}
    with:
      image-names: appointment-frontend feedback-api notifications-api queue-management-api queue-management-frontend send-appointment-reminder-crond
      tag-from: ${{ needs.approve-theq-prod.outputs.image-tags }}
      tag-to: prod

  ##### DEPLOY QMS #################################################################################

  approve-qms-dev:
    name: Approve Deploy to QMS Dev
    needs: [appointment-frontend, feedback-api, notifications-api, queue-management-api, queue-management-frontend, send-appointment-reminder-crond]
    environment: QMS Dev
    runs-on: ubuntu-latest

    steps:
      - name: Deployment Approval
        run: echo Approved

  tag-qms-dev:
    name: Tag QMS Dev
    needs: [create-image-tags, approve-qms-dev]
    uses: walter-moar/queue-management/.github/workflows/reusable-tag-image.yaml@master
    secrets:
      licence-plate: ${{ secrets.LICENCE_PLATE_QMS }}
      openshift-api: ${{ secrets.OPENSHIFT_API }}
      token: ${{ secrets.SA_PASSWORD_QMS_TOOLS }}
    with:
      image-names: appointment-frontend feedback-api notifications-api queue-management-api queue-management-frontend send-appointment-reminder-crond
      tag-from: ${{ needs.create-image-tags.outputs.image-tags }}
      tag-to: dev

  approve-qms-test:
    name: Approve Deploy to QMS Test
    needs: tag-qms-dev
    environment: QMS Test
    runs-on: ubuntu-latest

    steps:
      - name: Deployment Approval
        run: echo Approved

  tag-qms-test:
    name: Tag QMS Test
    needs: [create-image-tags, approve-qms-test]
    uses: walter-moar/queue-management/.github/workflows/reusable-tag-image.yaml@master
    secrets:
      licence-plate: ${{ secrets.LICENCE_PLATE_QMS }}
      openshift-api: ${{ secrets.OPENSHIFT_API }}
      token: ${{ secrets.SA_PASSWORD_QMS_TOOLS }}
    with:
      image-names: appointment-frontend feedback-api notifications-api queue-management-api queue-management-frontend send-appointment-reminder-crond
      tag-from: ${{ needs.create-image-tags.outputs.image-tags }}
      tag-to: test

  approve-qms-prod:
    name: Approve Deploy to QMS Prod
    needs: tag-qms-test
    environment: QMS Prod
    runs-on: ubuntu-latest

    steps:
      - name: Deployment Approval
        run: echo Approved

  tag-qms-prod:
    name: Tag QMS Prod
    needs: [create-image-tags, approve-qms-prod]
    uses: walter-moar/queue-management/.github/workflows/reusable-tag-image.yaml@master
    secrets:
      licence-plate: ${{ secrets.LICENCE_PLATE_QMS }}
      openshift-api: ${{ secrets.OPENSHIFT_API }}
      token: ${{ secrets.SA_PASSWORD_QMS_TOOLS }}
    with:
      image-names: appointment-frontend feedback-api notifications-api queue-management-api queue-management-frontend send-appointment-reminder-crond
      tag-from: ${{ needs.create-image-tags.outputs.image-tags }}
      tag-to: prod
