name: Lint
on:
  workflow_call:
    inputs:
      continue-on-error:
        required: false
        type: boolean
        default: false
      directory:
        required: false
        type: string
        default: .

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }}

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: NPM Install
        run: |
          cd ${{ inputs.directory }}
          npm install

      - name: Run Lint
        run: |
          cd ${{ inputs.directory }}
          npm run lint
