name: Pylint
on:
  workflow_call:
    inputs:
      continue-on-error:
        required: false
        type: boolean
        default: false
      directory:
        required: false
        type: string
        default: .
      target:
        required: true
        type: string

jobs:
  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }}

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Install Requirements
        run: |
          cd ${{ inputs.directory }}
          python -m venv env
          source env/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt pylint

      - name: Run Pylint
        run: |
          cd ${{ inputs.directory }}
          source env/bin/activate
          pylint ${{ inputs.target }}
